// ─── Saga Definitions (Extended Templates) ────────────────────────────────
// Extended sagas 5-8: Renewal, Upgrade, Downgrade, Reactivation + dispatcher

use super::types::*;

/// Get the Saga definition for Subscription Renewal
pub(crate) fn renewal_saga() -> SagaDefinition {
    SagaDefinition {
        saga_type: SagaType::Renewal,
        version: "1.0.0".to_string(),
        description: "Orchestrates subscription renewal with payment verification and usage reset.".to_string(),
        steps: vec![
            SagaStepDefinition {
                step_index: 0,
                step_name: "validate_renewal".to_string(),
                description: "Validate that the subscription is eligible for renewal".to_string(),
                action: "validate_subscription_renewable".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 1,
                step_name: "create_renewal_payment_request".to_string(),
                description: "Create payment request for the renewal amount".to_string(),
                action: "db_create_payment_request".to_string(),
                compensating_action: "db_delete_payment_request".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 2,
                step_name: "await_payment_confirmation".to_string(),
                description: "Wait for admin to confirm USDT TRC20 renewal payment".to_string(),
                action: "await_admin_confirmation".to_string(),
                compensating_action: "mark_payment_as_expired".to_string(),
                is_critical: true,
                timeout_ms: 86400000,
                retry_count: 0,
                requires_external_input: true,
            },
            SagaStepDefinition {
                step_index: 3,
                step_name: "extend_subscription_period".to_string(),
                description: "Extend the subscription period by 30 days".to_string(),
                action: "db_extend_subscription_period".to_string(),
                compensating_action: "db_revert_subscription_period".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 4,
                step_name: "reset_usage_records".to_string(),
                description: "Reset usage counters for the new billing period".to_string(),
                action: "db_reset_usage_records".to_string(),
                compensating_action: "db_restore_usage_records".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 5,
                step_name: "create_renewal_audit".to_string(),
                description: "Create audit log for the renewal".to_string(),
                action: "create_audit_entry".to_string(),
                compensating_action: "mark_audit_as_rolled_back".to_string(),
                is_critical: false,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
        ],
        timeout_ms: 172800000,
        max_retries: 1,
        payment_currency: "USDT".to_string(),
        payment_network: "TRC20".to_string(),
    }
}

/// Get the Saga definition for Tier Upgrade
pub(crate) fn upgrade_saga() -> SagaDefinition {
    SagaDefinition {
        saga_type: SagaType::Upgrade,
        version: "1.0.0".to_string(),
        description: "Orchestrates tier upgrade with proration calculation and feature activation.".to_string(),
        steps: vec![
            SagaStepDefinition {
                step_index: 0,
                step_name: "validate_upgrade".to_string(),
                description: "Validate that the upgrade is valid (new tier > current tier)".to_string(),
                action: "validate_upgrade_path".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 1,
                step_name: "calculate_proration".to_string(),
                description: "Calculate prorated amount for the upgrade".to_string(),
                action: "calculate_proration_amount".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 2,
                step_name: "create_upgrade_payment_request".to_string(),
                description: "Create payment request for the prorated upgrade amount".to_string(),
                action: "db_create_payment_request".to_string(),
                compensating_action: "db_delete_payment_request".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 3,
                step_name: "await_payment_confirmation".to_string(),
                description: "Wait for admin to confirm USDT TRC20 upgrade payment".to_string(),
                action: "await_admin_confirmation".to_string(),
                compensating_action: "mark_payment_as_expired".to_string(),
                is_critical: true,
                timeout_ms: 86400000,
                retry_count: 0,
                requires_external_input: true,
            },
            SagaStepDefinition {
                step_index: 4,
                step_name: "update_subscription_tier".to_string(),
                description: "Update subscription to the new tier".to_string(),
                action: "db_update_subscription_tier".to_string(),
                compensating_action: "db_revert_subscription_tier".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 5,
                step_name: "activate_new_features".to_string(),
                description: "Activate features available in the new tier".to_string(),
                action: "update_feature_gates_for_tier".to_string(),
                compensating_action: "revert_feature_gates_to_previous_tier".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 6,
                step_name: "create_upgrade_audit".to_string(),
                description: "Create audit log for the upgrade".to_string(),
                action: "create_audit_entry".to_string(),
                compensating_action: "mark_audit_as_rolled_back".to_string(),
                is_critical: false,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
        ],
        timeout_ms: 172800000,
        max_retries: 1,
        payment_currency: "USDT".to_string(),
        payment_network: "TRC20".to_string(),
    }
}

/// Get the Saga definition for Tier Downgrade
pub(crate) fn downgrade_saga() -> SagaDefinition {
    SagaDefinition {
        saga_type: SagaType::Downgrade,
        version: "1.0.0".to_string(),
        description: "Orchestrates tier downgrade with feature revocation and proration credit.".to_string(),
        steps: vec![
            SagaStepDefinition {
                step_index: 0,
                step_name: "validate_downgrade".to_string(),
                description: "Validate that the downgrade is valid (new tier < current tier)".to_string(),
                action: "validate_downgrade_path".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 1,
                step_name: "identify_revocable_features".to_string(),
                description: "Identify features that will be revoked in the lower tier".to_string(),
                action: "identify_features_to_revoke".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 2,
                step_name: "calculate_proration_credit".to_string(),
                description: "Calculate prorated credit for the downgrade".to_string(),
                action: "calculate_proration_credit".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 3,
                step_name: "update_subscription_tier".to_string(),
                description: "Update subscription to the lower tier".to_string(),
                action: "db_update_subscription_tier".to_string(),
                compensating_action: "db_revert_subscription_tier".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 4,
                step_name: "revoke_features".to_string(),
                description: "Revoke features not available in the lower tier".to_string(),
                action: "revoke_features_for_downgrade".to_string(),
                compensating_action: "restore_revoked_features".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 5,
                step_name: "create_downgrade_audit".to_string(),
                description: "Create audit log for the downgrade".to_string(),
                action: "create_audit_entry".to_string(),
                compensating_action: "mark_audit_as_rolled_back".to_string(),
                is_critical: false,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
        ],
        timeout_ms: 120000,
        max_retries: 1,
        payment_currency: "USDT".to_string(),
        payment_network: "TRC20".to_string(),
    }
}

/// Get the Saga definition for Subscription Reactivation
pub(crate) fn reactivation_saga() -> SagaDefinition {
    SagaDefinition {
        saga_type: SagaType::Reactivation,
        version: "1.0.0".to_string(),
        description: "Orchestrates reactivation of a cancelled subscription.".to_string(),
        steps: vec![
            SagaStepDefinition {
                step_index: 0,
                step_name: "validate_reactivation".to_string(),
                description: "Validate that the subscription can be reactivated".to_string(),
                action: "validate_subscription_reactivatable".to_string(),
                compensating_action: "none".to_string(),
                is_critical: true,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 1,
                step_name: "create_reactivation_payment".to_string(),
                description: "Create payment request for reactivation".to_string(),
                action: "db_create_payment_request".to_string(),
                compensating_action: "db_delete_payment_request".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 2,
                step_name: "await_payment_confirmation".to_string(),
                description: "Wait for admin to confirm USDT TRC20 reactivation payment".to_string(),
                action: "await_admin_confirmation".to_string(),
                compensating_action: "mark_payment_as_expired".to_string(),
                is_critical: true,
                timeout_ms: 86400000,
                retry_count: 0,
                requires_external_input: true,
            },
            SagaStepDefinition {
                step_index: 3,
                step_name: "reactivate_subscription".to_string(),
                description: "Update subscription status back to active".to_string(),
                action: "db_reactivate_subscription".to_string(),
                compensating_action: "db_cancel_subscription".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 4,
                step_name: "restore_feature_gates".to_string(),
                description: "Restore feature gate access for the tier".to_string(),
                action: "restore_feature_gates".to_string(),
                compensating_action: "revoke_all_feature_gates".to_string(),
                is_critical: true,
                timeout_ms: 10000,
                retry_count: 2,
                requires_external_input: false,
            },
            SagaStepDefinition {
                step_index: 5,
                step_name: "create_reactivation_audit".to_string(),
                description: "Create audit log for the reactivation".to_string(),
                action: "create_audit_entry".to_string(),
                compensating_action: "mark_audit_as_rolled_back".to_string(),
                is_critical: false,
                timeout_ms: 5000,
                retry_count: 1,
                requires_external_input: false,
            },
        ],
        timeout_ms: 172800000,
        max_retries: 1,
        payment_currency: "USDT".to_string(),
        payment_network: "TRC20".to_string(),
    }
}

/// Get a Saga definition by type
pub fn get_saga_definition(saga_type: SagaType) -> SagaDefinition {
    match saga_type {
        SagaType::TrialCreation => super::definitions_core::trial_creation_saga(),
        SagaType::TrialConversion => super::definitions_core::trial_conversion_saga(),
        SagaType::PaymentVerification => super::definitions_core::payment_verification_saga(),
        SagaType::Cancellation => super::definitions_core::cancellation_saga(),
        SagaType::Renewal => renewal_saga(),
        SagaType::Upgrade => upgrade_saga(),
        SagaType::Downgrade => downgrade_saga(),
        SagaType::Reactivation => reactivation_saga(),
    }
}
