"""
Zenic-Agents ROI Dashboard Package

Tracks operational costs, value generated by automation, and economic
impact scoring.  Aggregates everything into executive dashboard
metrics, widgets, and trend data.

Components:
- CostAccumulator:  Per-action cost tracking (LLM tokens, API calls, etc.)
- ValueTracker:     Automation value tracking (hours saved, errors avoided, etc.)
- ImpactScorer:     Economic impact scoring per alert/event/action
- ROIDashboardData: Aggregated dashboard metrics, widgets, and trends

Quick start::

    from src.core.roi import get_cost_accumulator, get_value_tracker

    acc = get_cost_accumulator()
    acc.record_action_cost("action-1", llm_tokens=1500, api_calls=3)

    vt = get_value_tracker()
    vt.record_automation_value(hours_saved=5, errors_avoided=2)
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# ── Cost Accumulator ─────────────────────────────────────

try:
    from .cost_accumulator import (  # noqa: F401
        CostAccumulator,
        CostCategory,
        CostEntry,
        get_cost_accumulator,
        reset_cost_accumulator,
    )
except Exception as _exc:  # noqa: BLE001
    logger.warning("roi: CostAccumulator import failed: %s", _exc)
    CostAccumulator = None  # type: ignore[assignment,misc]
    CostCategory = None  # type: ignore[assignment,misc]
    CostEntry = None  # type: ignore[assignment,misc]
    get_cost_accumulator = None  # type: ignore[assignment,misc]
    reset_cost_accumulator = None  # type: ignore[assignment,misc]

# ── Value Tracker ────────────────────────────────────────

try:
    from .value_tracker import (  # noqa: F401
        ValueTracker,
        ValueCategory,
        ValueEntry,
        get_value_tracker,
        reset_value_tracker,
    )
except Exception as _exc:  # noqa: BLE001
    logger.warning("roi: ValueTracker import failed: %s", _exc)
    ValueTracker = None  # type: ignore[assignment,misc]
    ValueCategory = None  # type: ignore[assignment,misc]
    ValueEntry = None  # type: ignore[assignment,misc]
    get_value_tracker = None  # type: ignore[assignment,misc]
    reset_value_tracker = None  # type: ignore[assignment,misc]

# ── Impact Scorer ────────────────────────────────────────

try:
    from .impact_scorer import (  # noqa: F401
        ImpactScorer,
        ImpactScore,
        get_impact_scorer,
        reset_impact_scorer,
    )
except Exception as _exc:  # noqa: BLE001
    logger.warning("roi: ImpactScorer import failed: %s", _exc)
    ImpactScorer = None  # type: ignore[assignment,misc]
    ImpactScore = None  # type: ignore[assignment,misc]
    get_impact_scorer = None  # type: ignore[assignment,misc]
    reset_impact_scorer = None  # type: ignore[assignment,misc]

# ── Dashboard Data ───────────────────────────────────────

try:
    from .dashboard_data import (  # noqa: F401
        ROIDashboardData,
        DashboardWidget,
        TrendPoint,
        get_roi_dashboard_data,
        reset_roi_dashboard_data,
    )
except Exception as _exc:  # noqa: BLE001
    logger.warning("roi: ROIDashboardData import failed: %s", _exc)
    ROIDashboardData = None  # type: ignore[assignment,misc]
    DashboardWidget = None  # type: ignore[assignment,misc]
    TrendPoint = None  # type: ignore[assignment,misc]
    get_roi_dashboard_data = None  # type: ignore[assignment,misc]
    reset_roi_dashboard_data = None  # type: ignore[assignment,misc]

# ── Public API ───────────────────────────────────────────

__all__ = [
    # Cost Accumulator
    "CostAccumulator",
    "CostCategory",
    "CostEntry",
    "get_cost_accumulator",
    "reset_cost_accumulator",
    # Value Tracker
    "ValueTracker",
    "ValueCategory",
    "ValueEntry",
    "get_value_tracker",
    "reset_value_tracker",
    # Impact Scorer
    "ImpactScorer",
    "ImpactScore",
    "get_impact_scorer",
    "reset_impact_scorer",
    # Dashboard Data
    "ROIDashboardData",
    "DashboardWidget",
    "TrendPoint",
    "get_roi_dashboard_data",
    "reset_roi_dashboard_data",
]
