//! YAML Renderer — Declarative YAML for zenic-policy hot-reload [T2-8, T2-14, T2-15]
//!
//! After HITL approval, the approved mapping is rendered as YAML
//! for hot-reload into the zenic-policy engine.
//!
//! The YAML renderer VALIDATES the MemoryApprovalRequest before rendering.
//! If the request doesn't pass validation, the YAML is NOT compiled.

use crate::errors::MemoryError;
use crate::types::{MemoryApprovalRequest, SemanticMapping};

// ---------------------------------------------------------------------------
// YamlRenderer
// ---------------------------------------------------------------------------

/// Renders approved semantic mappings as declarative YAML for hot-reload.
///
/// Flow:
// 1. HITL approves with 3 mandatory fields
// 2. YamlRenderer validates MemoryApprovalRequest
// 3. If valid → renders YAML
// 4. zenic-policy hot-reloads the YAML (30s cycle)
pub struct YamlRenderer {
    /// Whether to include evidence details in the output.
    include_evidence: bool,
    /// Whether to include IA classification details.
    include_ia_details: bool,
}

impl YamlRenderer {
    /// Creates a new YAML renderer.
    pub fn new() -> Self {
        Self {
            include_evidence: true,
            include_ia_details: true,
        }
    }

    /// Renders an approved mapping as YAML for policy hot-reload.
    ///
    /// Validates the MemoryApprovalRequest first — if it fails,
    /// returns an error and the YAML is NOT compiled.
    pub fn render_mapping(
        &self,
        mapping: &SemanticMapping,
        approval: &MemoryApprovalRequest,
    ) -> Result<String, MemoryError> {
        // GRIETA 3: Validate before rendering
        approval.validate()?;

        let mut yaml = String::from("# Auto-generated by zenic-memory Chip\n");
        yaml.push_str("# DO NOT EDIT — managed by Adaptive Binary Memory\n");
        yaml.push_str("---\n");
        yaml.push_str(&format!("mapping_id: \"{}\"\n", mapping.mapping_id));
        yaml.push_str(&format!("origin: \"{}\"\n", mapping.origin));
        yaml.push_str(&format!("relation: \"{}\"\n", mapping.relation));
        yaml.push_str(&format!("destination: \"{}\"\n", mapping.destination));
        yaml.push_str(&format!("mechanism: \"{}\"\n", mapping.mechanism));
        yaml.push_str(&format!("confidence: {}\n", mapping.confidence));
        yaml.push_str(&format!("tenant_id: \"{}\"\n", mapping.tenant_id));
        yaml.push_str(&format!("approved: true\n"));

        if let Some(ref hash) = mapping.merkle_hash {
            yaml.push_str(&format!("merkle_hash: \"{}\"\n", hash));
        }

        // HITL audit trail
        yaml.push_str("\n# HITL Audit Trail\n");
        yaml.push_str(&format!(
            "admin_evidence_review: {}\n",
            approval.admin_evidence_review
        ));
        yaml.push_str(&format!(
            "admin_justification: |\n  {}\n",
            approval.admin_justification
        ));
        yaml.push_str(&format!(
            "risk_acknowledgment: {}\n",
            approval.risk_acknowledgment
        ));
        yaml.push_str(&format!(
            "admin_session_id: \"{}\"\n",
            approval.admin_session_id
        ));

        if self.include_ia_details {
            yaml.push_str("\n# IA Classification\n");
            yaml.push_str(&format!("ia_question: \"{}\"\n", approval.ia_question));
            yaml.push_str(&format!(
                "ia_response: \"{}\"\n",
                if approval.ia_response { "YES" } else { "NO" }
            ));
            yaml.push_str(&format!("consensus_score: {:.4}\n", approval.consensus_score));
        }

        if self.include_evidence {
            yaml.push_str("\n# Evidence\n");
            yaml.push_str("evidence_for:\n");
            for ev in &approval.evidence_for {
                yaml.push_str(&format!("  - \"{}\"\n", ev));
            }
            yaml.push_str("evidence_against:\n");
            for ev in &approval.evidence_against {
                yaml.push_str(&format!("  - \"{}\"\n", ev));
            }
        }

        Ok(yaml)
    }

    /// Renders a simple key-value map as YAML.
    pub fn render_simple(&self, data: &[(&str, &str)]) -> String {
        let mut output = String::from("---\n");
        for (key, value) in data {
            output.push_str(&format!("{}: \"{}\"\n", key, value));
        }
        output
    }

    /// Sets whether to include evidence details.
    pub fn with_evidence(mut self, include: bool) -> Self {
        self.include_evidence = include;
        self
    }

    /// Sets whether to include IA classification details.
    pub fn with_ia_details(mut self, include: bool) -> Self {
        self.include_ia_details = include;
        self
    }
}

impl Default for YamlRenderer {
    fn default() -> Self {
        Self::new()
    }
}
