//! YAML Renderer — Declarative YAML for zenic-policy hot-reload [T2-8, T2-14, T2-15]
//!
//! After HITL approval, the approved mapping is rendered as YAML
//! for hot-reload into the zenic-policy engine.
//!
//! The YAML renderer VALIDATES the MemoryApprovalRequest before rendering.
//! If the request doesn't pass validation, the YAML is NOT compiled.
//!
//! Phase 4 enhancements:
//! - Hot-reload format: renders YAML in the exact format zenic-policy
//!   expects for its 30-second hot-reload cycle
//! - Batch rendering: multiple mappings in a single YAML document
//! - Validation before rendering enforced for all render methods

use crate::errors::MemoryError;
use crate::types::{MemoryApprovalRequest, SemanticMapping};

// ---------------------------------------------------------------------------
// YamlRenderer
// ---------------------------------------------------------------------------

/// Renders approved semantic mappings as declarative YAML for hot-reload.
///
/// Flow:
/// 1. HITL approves with 3 mandatory fields
/// 2. YamlRenderer validates MemoryApprovalRequest
/// 3. If valid → renders YAML
/// 4. zenic-policy hot-reloads the YAML (30s cycle)
pub struct YamlRenderer {
    /// Whether to include evidence details in the output.
    include_evidence: bool,
    /// Whether to include IA classification details.
    include_ia_details: bool,
}

impl YamlRenderer {
    /// Creates a new YAML renderer.
    pub fn new() -> Self {
        Self {
            include_evidence: true,
            include_ia_details: true,
        }
    }

    /// Renders an approved mapping as YAML for policy hot-reload.
    ///
    /// Validates the MemoryApprovalRequest first — if it fails,
    /// returns an error and the YAML is NOT compiled.
    pub fn render_mapping(
        &self,
        mapping: &SemanticMapping,
        approval: &MemoryApprovalRequest,
    ) -> Result<String, MemoryError> {
        // GRIETA 3: Validate before rendering
        approval.validate()?;

        let mut yaml = String::from("# Auto-generated by zenic-memory Chip\n");
        yaml.push_str("# DO NOT EDIT — managed by Adaptive Binary Memory\n");
        yaml.push_str("---\n");
        yaml.push_str(&format!("mapping_id: \"{}\"\n", mapping.mapping_id));
        yaml.push_str(&format!("origin: \"{}\"\n", mapping.origin));
        yaml.push_str(&format!("relation: \"{}\"\n", mapping.relation));
        yaml.push_str(&format!("destination: \"{}\"\n", mapping.destination));
        yaml.push_str(&format!("mechanism: \"{}\"\n", mapping.mechanism));
        yaml.push_str(&format!("confidence: {}\n", mapping.confidence));
        yaml.push_str(&format!("tenant_id: \"{}\"\n", mapping.tenant_id));
        yaml.push_str(&format!("approved: true\n"));

        if let Some(ref hash) = mapping.merkle_hash {
            yaml.push_str(&format!("merkle_hash: \"{}\"\n", hash));
        }

        // HITL audit trail
        yaml.push_str("\n# HITL Audit Trail\n");
        yaml.push_str(&format!(
            "admin_evidence_review: {}\n",
            approval.admin_evidence_review
        ));
        yaml.push_str(&format!(
            "admin_justification: |\n  {}\n",
            approval.admin_justification
        ));
        yaml.push_str(&format!(
            "risk_acknowledgment: {}\n",
            approval.risk_acknowledgment
        ));
        yaml.push_str(&format!(
            "admin_session_id: \"{}\"\n",
            approval.admin_session_id
        ));

        if self.include_ia_details {
            yaml.push_str("\n# IA Classification\n");
            yaml.push_str(&format!("ia_question: \"{}\"\n", escape_yaml_string(&approval.ia_question)));
            yaml.push_str(&format!(
                "ia_response: \"{}\"\n",
                if approval.ia_response { "YES" } else { "NO" }
            ));
            yaml.push_str(&format!("consensus_score: {:.4}\n", approval.consensus_score));
        }

        if self.include_evidence {
            yaml.push_str("\n# Evidence\n");
            yaml.push_str("evidence_for:\n");
            for ev in &approval.evidence_for {
                yaml.push_str(&format!("  - \"{}\"\n", escape_yaml_string(ev)));
            }
            yaml.push_str("evidence_against:\n");
            for ev in &approval.evidence_against {
                yaml.push_str(&format!("  - \"{}\"\n", escape_yaml_string(ev)));
            }
        }

        Ok(yaml)
    }

    /// Renders an approved mapping in the hot-reload YAML format.
    ///
    /// This is the exact format zenic-policy expects for its 30-second
    /// hot-reload cycle. Validates the MemoryApprovalRequest BEFORE
    /// any YAML is generated.
    ///
    /// # Format
    ///
    /// ```yaml
    /// # Auto-generated by Zenic Memory Chip — DO NOT EDIT MANUALLY
    /// # Approved by: <session_id_prefix>...
    /// # Merkle hash: <blake3_hash>
    /// # Timestamp: <iso8601>
    /// mappings:
    ///   - origin: "cobro"
    ///     relation: "synonym_of"
    ///     ...
    /// ```
    pub fn render_for_hot_reload(
        &self,
        mapping: &SemanticMapping,
        approval: &MemoryApprovalRequest,
    ) -> Result<String, MemoryError> {
        // VALIDATE BEFORE RENDERING — non-negotiable
        approval.validate()?;

        let timestamp = format_iso8601(mapping.created_at);
        let session_preview = truncate_session_id(&approval.admin_session_id, 8);
        let merkle_hash = mapping
            .merkle_hash
            .as_deref()
            .unwrap_or("<not_sealed>");

        let mut yaml = String::new();

        // Header comments
        yaml.push_str("# Auto-generated by Zenic Memory Chip — DO NOT EDIT MANUALLY\n");
        yaml.push_str(&format!("# Approved by: {}...\n", session_preview));
        yaml.push_str(&format!("# Merkle hash: {}\n", merkle_hash));
        yaml.push_str(&format!("# Timestamp: {}\n", timestamp));

        // Mappings block
        yaml.push_str("mappings:\n");
        yaml.push_str(&Self::render_mapping_entry(mapping, approval));

        Ok(yaml)
    }

    /// Renders multiple mappings into a single YAML document.
    ///
    /// Validates ALL MemoryApprovalRequests before rendering any YAML.
    /// If any request fails validation, returns an error without
    /// generating any output.
    pub fn render_batch(
        &self,
        mappings: &[(SemanticMapping, MemoryApprovalRequest)],
    ) -> Result<String, MemoryError> {
        // Validate ALL requests before rendering ANY YAML
        for (_, approval) in mappings {
            approval.validate()?;
        }

        if mappings.is_empty() {
            return Ok("# Auto-generated by Zenic Memory Chip — DO NOT EDIT MANUALLY\nmappings: []\n".to_string());
        }

        let first_mapping = &mappings[0].0;
        let first_approval = &mappings[0].1;
        let timestamp = format_iso8601(first_mapping.created_at);
        let session_preview = truncate_session_id(&first_approval.admin_session_id, 8);

        let mut yaml = String::new();

        // Header comments (use first mapping's info)
        yaml.push_str("# Auto-generated by Zenic Memory Chip — DO NOT EDIT MANUALLY\n");
        yaml.push_str(&format!("# Approved by: {}...\n", session_preview));
        yaml.push_str(&format!("# Batch size: {} mapping(s)\n", mappings.len()));
        yaml.push_str(&format!("# Timestamp: {}\n", timestamp));

        // Mappings block
        yaml.push_str("mappings:\n");
        for (mapping, approval) in mappings {
            yaml.push_str(&Self::render_mapping_entry(mapping, approval));
        }

        Ok(yaml)
    }

    /// Renders a single mapping entry (indented for inclusion in `mappings:` block).
    fn render_mapping_entry(mapping: &SemanticMapping, approval: &MemoryApprovalRequest) -> String {
        let mut entry = String::new();

        entry.push_str(&format!("  - origin: \"{}\"\n", escape_yaml_string(&mapping.origin)));
        entry.push_str(&format!("    relation: \"{}\"\n", escape_yaml_string(&mapping.relation)));
        entry.push_str(&format!(
            "    destination: \"{}\"\n",
            escape_yaml_string(&mapping.destination)
        ));
        entry.push_str(&format!("    mechanism: {}\n", mapping.mechanism));
        entry.push_str(&format!("    confidence: {}\n", mapping.confidence));
        entry.push_str("    approved: true\n");

        // Audit sub-object
        entry.push_str("    audit:\n");
        entry.push_str(&format!(
            "      ia_question: \"{}\"\n",
            escape_yaml_string(&approval.ia_question)
        ));
        entry.push_str(&format!(
            "      ia_response: {}\n",
            approval.ia_response
        ));

        // Evidence for
        entry.push_str("      evidence_for:\n");
        for ev in &approval.evidence_for {
            entry.push_str(&format!("        - \"{}\"\n", escape_yaml_string(ev)));
        }

        // Evidence against
        entry.push_str("      evidence_against:\n");
        for ev in &approval.evidence_against {
            entry.push_str(&format!("        - \"{}\"\n", escape_yaml_string(ev)));
        }

        // Consensus score
        entry.push_str(&format!("      consensus_score: {:.2}\n", approval.consensus_score));

        // Admin justification (truncated to first 80 chars)
        let just_truncated = truncate_str(&approval.admin_justification, 80);
        entry.push_str(&format!(
            "      admin_justification: \"{}...\"\n",
            escape_yaml_string(&just_truncated)
        ));

        entry
    }

    /// Renders a simple key-value map as YAML.
    pub fn render_simple(&self, data: &[(&str, &str)]) -> String {
        let mut output = String::from("---\n");
        for (key, value) in data {
            output.push_str(&format!("{}: \"{}\"\n", key, value));
        }
        output
    }

    /// Sets whether to include evidence details.
    pub fn with_evidence(mut self, include: bool) -> Self {
        self.include_evidence = include;
        self
    }

    /// Sets whether to include IA classification details.
    pub fn with_ia_details(mut self, include: bool) -> Self {
        self.include_ia_details = include;
        self
    }
}

impl Default for YamlRenderer {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Escapes a string for safe YAML double-quoted representation.
fn escape_yaml_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\t', "\\t")
}

/// Truncates a string to at most `max_len` characters.
fn truncate_str(s: &str, max_len: usize) -> String {
    if s.len() <= max_len {
        s.to_string()
    } else {
        s[..max_len].to_string()
    }
}

/// Truncates a session ID for security display (shows first N chars).
fn truncate_session_id(session_id: &str, show_chars: usize) -> String {
    if session_id.len() <= show_chars {
        session_id.to_string()
    } else {
        session_id[..show_chars].to_string()
    }
}

/// Formats a Unix epoch millis timestamp as an ISO 8601 string.
fn format_iso8601(epoch_millis: i64) -> String {
    // Simple ISO 8601 format from epoch millis
    let secs = epoch_millis / 1000;
    let millis = epoch_millis % 1000;

    // Compute date components from epoch seconds
    let days_since_epoch = secs / 86400;
    let time_secs = secs % 86400;

    let hours = time_secs / 3600;
    let minutes = (time_secs % 3600) / 60;
    let seconds = time_secs % 60;

    // Compute year/month/day using algorithm for Gregorian calendar
    let (year, month, day) = days_to_ymd(days_since_epoch);

    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}.{:03}Z",
        year, month, day, hours, minutes, seconds, millis
    )
}

/// Converts days since Unix epoch to (year, month, day).
fn days_to_ymd(days: i64) -> (i64, i64, i64) {
    // Algorithm from http://howardhinnant.github.io/date_algorithms.html
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}
