"""
Zenic-Agents Asistente - SNA Types

Core type definitions for the Sistema Nervioso Autónomo (SNA).
All dataclasses, enums, and value objects used across the SNA subsystem.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ──────────────────────────────────────────────────────────────
#  ENUMS
# ──────────────────────────────────────────────────────────────

class MonitorWeight(str, Enum):
    """Classification of monitor computational weight."""
    LIGHTWEIGHT = "lightweight"   # <100ms, simple DB queries
    MEDIUM = "medium"             # 100ms-1s, aggregations
    HEAVY = "heavy"               # >1s, multi-source analysis


class AlertSeverity(str, Enum):
    """Severity level for SNA alerts."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """Lifecycle status of an alert."""
    PENDING = "pending"       # Awaiting DAG dispatch
    DISPATCHED = "dispatched" # Sent to DAG pipeline
    NOTIFIED = "notified"     # User notified successfully
    ACKNOWLEDGED = "acknowledged"  # User acknowledged
    RESOLVED = "resolved"     # Condition resolved
    EXPIRED = "expired"       # Alert TTL expired


class ThresholdOperator(str, Enum):
    """Comparison operator for threshold evaluation."""
    GT = "gt"           # value > threshold
    GTE = "gte"         # value >= threshold
    LT = "lt"           # value < threshold
    LTE = "lte"         # value <= threshold
    EQ = "eq"           # value == threshold
    NEQ = "neq"         # value != threshold
    BETWEEN = "between" # low <= value <= high


class SchedulerState(str, Enum):
    """State of the SNA scheduler."""
    STOPPED = "stopped"
    RUNNING = "running"
    PAUSED = "paused"
    ERROR = "error"


# ──────────────────────────────────────────────────────────────
#  DATACLASSES
# ──────────────────────────────────────────────────────────────

@dataclass
class MonitorResult:
    """Result of a single monitor check execution."""
    monitor_id: str
    monitor_name: str
    triggered: bool
    value: Any = None
    detail: str = ""
    weight: MonitorWeight = MonitorWeight.LIGHTWEIGHT
    severity: AlertSeverity = AlertSeverity.INFO
    metadata: Dict[str, Any] = field(default_factory=dict)
    checked_at: float = 0.0
    duration_ms: float = 0.0

    def __post_init__(self) -> None:
        if not self.checked_at:
            self.checked_at = time.time()


@dataclass
class ThresholdConfig:
    """Configuration for a single threshold rule."""
    threshold_id: str
    monitor_id: str
    field_name: str
    operator: ThresholdOperator
    value: float
    value_high: Optional[float] = None  # For BETWEEN operator
    severity: AlertSeverity = AlertSeverity.WARNING
    cooldown_seconds: float = 300.0     # Min time between same alerts
    tenant_id: str = ""
    blueprint_name: str = ""

    def evaluate(self, actual_value: float) -> bool:
        """Evaluate whether the threshold is breached."""
        op = self.operator
        if op == ThresholdOperator.GT:
            return actual_value > self.value
        if op == ThresholdOperator.GTE:
            return actual_value >= self.value
        if op == ThresholdOperator.LT:
            return actual_value < self.value
        if op == ThresholdOperator.LTE:
            return actual_value <= self.value
        if op == ThresholdOperator.EQ:
            return abs(actual_value - self.value) < 1e-9
        if op == ThresholdOperator.NEQ:
            return abs(actual_value - self.value) >= 1e-9
        if op == ThresholdOperator.BETWEEN:
            low = self.value
            high = self.value_high if self.value_high is not None else self.value
            return low <= actual_value <= high
        return False


@dataclass
class Alert:
    """An alert generated by the SNA system."""
    alert_id: str = ""
    monitor_id: str = ""
    monitor_name: str = ""
    severity: AlertSeverity = AlertSeverity.WARNING
    status: AlertStatus = AlertStatus.PENDING
    title: str = ""
    message: str = ""
    value: Any = None
    threshold: Optional[ThresholdConfig] = None
    tenant_id: str = ""
    channel: str = ""              # Preferred notification channel
    dispatch_actions: List[Dict[str, Any]] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: float = 0.0
    dispatched_at: float = 0.0
    notified_at: float = 0.0
    acknowledged_at: float = 0.0
    ttl_seconds: float = 3600.0    # Alert expires after 1 hour by default

    def __post_init__(self) -> None:
        if not self.alert_id:
            self.alert_id = uuid.uuid4().hex[:12]
        if not self.created_at:
            self.created_at = time.time()

    @property
    def is_expired(self) -> bool:
        """Check if alert has exceeded its TTL."""
        return time.time() > (self.created_at + self.ttl_seconds)


@dataclass
class MonitorConfig:
    """Configuration for a scheduled monitor."""
    monitor_id: str
    monitor_name: str
    weight: MonitorWeight = MonitorWeight.LIGHTWEIGHT
    interval_seconds: float = 300.0   # Default 5 minutes
    enabled: bool = True
    tenant_id: str = ""
    blueprint_name: str = ""
    params: Dict[str, Any] = field(default_factory=dict)
    notification_channel: str = "log"
    priority: int = 5   # 0=critical, 10=low (for scheduler priority queue)

    @property
    def effective_interval(self) -> float:
        """Interval adjusted by weight category."""
        weight_multipliers = {
            MonitorWeight.LIGHTWEIGHT: 1.0,
            MonitorWeight.MEDIUM: 2.0,
            MonitorWeight.HEAVY: 4.0,
        }
        return self.interval_seconds * weight_multipliers.get(self.weight, 1.0)


@dataclass
class SNAStats:
    """Statistics for the SNA subsystem."""
    total_checks: int = 0
    total_triggered: int = 0
    total_alerts: int = 0
    total_dispatched: int = 0
    total_notified: int = 0
    active_monitors: int = 0
    active_alerts: int = 0
    scheduler_state: SchedulerState = SchedulerState.STOPPED
    last_check_time: float = 0.0
    scheduler_uptime_seconds: float = 0.0


# ──────────────────────────────────────────────────────────────
#  CONSTANTS
# ──────────────────────────────────────────────────────────────

# Default intervals by monitor weight
DEFAULT_INTERVALS: Dict[MonitorWeight, float] = {
    MonitorWeight.LIGHTWEIGHT: 300.0,   # 5 min
    MonitorWeight.MEDIUM: 600.0,        # 10 min
    MonitorWeight.HEAVY: 1800.0,        # 30 min
}

# Default alert channels by severity
DEFAULT_CHANNELS: Dict[AlertSeverity, str] = {
    AlertSeverity.INFO: "log",
    AlertSeverity.WARNING: "notification",
    AlertSeverity.CRITICAL: "telegram",
}

# Max alerts per tenant per hour (rate limiting)
MAX_ALERTS_PER_TENANT_PER_HOUR: int = 30
