"""
Zenic-Agents ROI — Value Tracker

Tracks value generated by automation: hours saved, errors avoided,
revenue recovered, tasks automated, response time improvements, and
compliance maintained.  Persists in SQLite with thread-safe access,
retry logic, and graceful degradation.
"""

import threading
from typing import Any, Optional

from ._types import ValueCategory, ValueEntry, DEFAULT_UNIT_VALUES
from ._mixin_core import ValueTracker

__all__ = [
    "ValueCategory",
    "ValueEntry",
    "ValueTracker",
    "DEFAULT_UNIT_VALUES",
    "get_value_tracker",
    "reset_value_tracker",
]


# ── Singleton ────────────────────────────────────────────

_value_tracker: Optional[ValueTracker] = None
_lock = threading.Lock()


def get_value_tracker(**kwargs: Any) -> ValueTracker:
    """Get or create the global ValueTracker singleton."""
    global _value_tracker
    with _lock:
        if _value_tracker is None:
            _value_tracker = ValueTracker(**kwargs)
        return _value_tracker


def reset_value_tracker() -> None:
    """Reset the global ValueTracker (for testing)."""
    global _value_tracker
    _value_tracker = None
