"""
Value Tracker — Types and helpers.

Contains ValueCategory enum, DEFAULT_UNIT_VALUES, ValueEntry dataclass,
and retry helper.
"""

from __future__ import annotations

import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class ValueCategory(str, Enum):
    """Categories of value generated by automation."""

    HOURS_SAVED = "hours_saved"
    ERRORS_AVOIDED = "errors_avoided"
    REVENUE_RECOVERED = "revenue_recovered"
    TASKS_AUTOMATED = "tasks_automated"
    RESPONSE_TIME_IMPROVED = "response_time_improved"
    COMPLIANCE_MAINTAINED = "compliance_maintained"


DEFAULT_UNIT_VALUES: Dict[ValueCategory, float] = {
    ValueCategory.HOURS_SAVED: 25.0,
    ValueCategory.ERRORS_AVOIDED: 150.0,
    ValueCategory.REVENUE_RECOVERED: 1.0,
    ValueCategory.TASKS_AUTOMATED: 10.0,
    ValueCategory.RESPONSE_TIME_IMPROVED: 5.0,
    ValueCategory.COMPLIANCE_MAINTAINED: 500.0,
}


@dataclass
class ValueEntry:
    """A single recorded value entry."""

    entry_id: str = ""
    category: ValueCategory = ValueCategory.HOURS_SAVED
    action_id: str = ""
    quantity: float = 0.0
    unit_value: float = 0.0
    total_value: float = 0.0
    currency: str = "USD"
    timestamp: str = ""
    tenant_id: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.entry_id:
            self.entry_id = uuid.uuid4().hex[:16]
        if not self.timestamp:
            self.timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        if self.total_value == 0.0 and (self.quantity != 0.0 or self.unit_value != 0.0):
            self.total_value = round(self.quantity * self.unit_value, 6)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a plain dict."""
        return {
            "entry_id": self.entry_id,
            "category": self.category.value,
            "action_id": self.action_id,
            "quantity": self.quantity,
            "unit_value": self.unit_value,
            "total_value": self.total_value,
            "currency": self.currency,
            "timestamp": self.timestamp,
            "tenant_id": self.tenant_id,
            "metadata": self.metadata,
        }


# ── Retry helper ─────────────────────────────────────────

_MAX_RETRIES = 3
_RETRY_BASE_DELAY = 0.1


def _with_retry(fn, label: str = "ValueTracker DB op"):
    """Execute *fn* with exponential-backoff retry (3 attempts)."""
    last_exc: Optional[Exception] = None
    for attempt in range(1, _MAX_RETRIES + 1):
        try:
            return fn()
        except Exception as exc:  # noqa: BLE001
            last_exc = exc
            if attempt < _MAX_RETRIES:
                delay = _RETRY_BASE_DELAY * (2 ** (attempt - 1))
                logger.debug(
                    "%s error (attempt %d/%d): %s — retrying in %.2fs",
                    label, attempt, _MAX_RETRIES, exc, delay,
                )
                time.sleep(delay)
            else:
                logger.warning(
                    "%s failed after %d attempts: %s", label, _MAX_RETRIES, exc,
                )
    if last_exc is not None:
        raise last_exc  # type: ignore[misc]
