"""MiniAIEngine bounded task methods (tasks 5-7) — PURELY DETERMINISTIC."""

import re
import logging
from typing import Any
logger = logging.getLogger("core.mini_ai_parts._tasks._tasks_5to7_mixin")

class BoundedTasks5To7Mixin:
    """Mixin providing tasks 5-7 for BoundedTasksMixin."""

    # ================================================================
    #  BOUNDED TASK 5: generate_pattern (template library)
    # ================================================================

    PATTERN_LIBRARY = {
        "python": {
            "async_await": "async def {name}({params}):\n    result = await {operation}({params})\n    return result\n",
            "validator": "def {name}(data: dict) -> bool:\n    required = {required_fields}\n    return all(k in data for k in required)\n",
            "repository": "class {class_name}:\n    def __init__(self, db):\n        self.db = db\n    def get_by_id(self, id: str):\n        return self.db.query(id)\n",
            "factory": "def create_{name}(type_: str):\n    handlers = {handler_map}\n    return handlers.get(type_, DefaultHandler)\n",
            "middleware": "def {name}(func):\n    def wrapper(*args, **kwargs):\n        pre_process(*args)\n        result = func(*args, **kwargs)\n        post_process(result)\n        return result\n    return wrapper\n",
            "observer": "class {class_name}:\n    def __init__(self):\n        self._observers = []\n    def subscribe(self, observer):\n        self._observers.append(observer)\n    def notify(self, event):\n        for obs in self._observers:\n            obs.on_event(event)\n",
            "security": "import hashlib, secrets\n\ndef hash_password(password: str) -> str:\n    salt = secrets.token_hex(16)\n    return hashlib.sha256((salt + password).encode()).hexdigest()\n",
            "cache": "from functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef {name}(key):\n    return expensive_lookup(key)\n",
            "singleton": "class {class_name}:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n",
            "default": "def {name}(data):\n    \"\"\"Generated by ZENIC-AGENTS v1\"\"\"\n    return data\n",
        },
        "javascript": {
            "async_await": "async function {name}({params}) {\n    const result = await {operation}({params});\n    return result;\n}\n",
            "validator": "function {name}(data) {\n    const required = {required_fields};\n    return required.every(k => k in data);\n}\n",
            "default": "function {name}(data) {\n    return data;\n}\n",
        },
        "typescript": {
            "default": "function {name}(data: any): any {\n    return data;\n}\n",
        },
        "kotlin": {
            "default": "fun {name}(data: Any): Any {\n    return data\n}\n",
        },
        "go": {
            "default": "func {name}(data interface{}) interface{} {{\n\treturn data\n}}\n",
        },
    }

    def generate_pattern(self, pattern_desc: str, language: str = "python") -> str:
        """
        Genera un snippet de código desde la librería de templates.

        100% determinístico. NUNCA llama al LLM.
        La IA NUNCA genera código. El código viene de templates
        probados y validados, no de generación probabilística.
        """
        lang_patterns = self.PATTERN_LIBRARY.get(language, self.PATTERN_LIBRARY["python"])

        # Buscar patrón por descripción
        desc_lower = pattern_desc.lower()
        pattern_name = "default"

        for keywords, name in self.PATTERN_HEURISTICS:
            if any(kw in desc_lower for kw in keywords):
                pattern_name = name
                break

        # Obtener template
        template = lang_patterns.get(pattern_name, lang_patterns.get("default", ""))

        # Formatear con placeholders seguros (no falla si faltan keys)
        try:
            result = template.format(
                name="generated",
                class_name="GeneratedClass",
                params="data",
                operation="process",
                required_fields="['id', 'name']",
                handler_map="{}",
            )
        except (KeyError, IndexError):
            result = template

        logger.debug(
            f"BoundedTasks.generate_pattern: {pattern_name} in {language} (deterministic)"
        )
        return result

    # ================================================================
    #  BOUNDED TASK 6: explain_violation (catalog-based)
    # ================================================================

    VIOLATION_CATALOG = {
        "exec_call": "Use of exec() allows arbitrary code execution, which is a critical security risk.",
        "eval_call": "Use of eval() allows arbitrary code execution, which is a critical security risk.",
        "import_call": "Dynamic import via __import__() can load untrusted modules at runtime.",
        "os_system": "os.system() executes shell commands, vulnerable to injection attacks.",
        "subprocess_call": "subprocess calls can execute arbitrary system commands.",
        "subprocess_popen": "subprocess.Popen() can spawn arbitrary processes.",
        "pickle_load": "pickle.loads() can deserialize malicious objects leading to RCE.",
        "yaml_unsafe": "yaml.load() without SafeLoader can execute arbitrary Python code.",
        "sensitive_file": "Access to sensitive system files (/etc, /proc, /sys) detected.",
        "rm_rf": "Dangerous rm -rf command detected, can destroy entire filesystems.",
        "socket_raw": "Raw socket creation detected, may indicate network-level exploits.",
        "null_pointer": "Potential null/None dereference detected.",
        "type_mismatch": "Type mismatch detected in function call.",
        "unreachable": "Unreachable code detected after return statement.",
        "unused_import": "Unused import detected.",
        "shutil_rmtree": "shutil.rmtree() can delete entire directory trees.",
        "ctypes": "ctypes usage detected - FFI access can bypass safety guarantees.",
    }

    def explain_violation(self, code: str, violations: list[str]) -> str:
        """
        Explica violaciones usando el catálogo de mensajes.

        100% determinístico. NUNCA llama al LLM.
        Mejora: Explicaciones consistentes, sin variabilidad.
        """
        if not violations:
            return "No violations detected."

        explanations = []
        for v in violations[:5]:  # Max 5 violations
            v_lower = v.lower()
            # Buscar en catálogo
            explanation = None
            for key, msg in self.VIOLATION_CATALOG.items():
                if key in v_lower or any(kw in v_lower for kw in key.split("_")):
                    explanation = msg
                    break

            if not explanation:
                explanation = f"Code violation detected: {v}"
            explanations.append(explanation)

        result = "; ".join(explanations)

        logger.debug(
            f"BoundedTasks.explain_violation: {len(violations)} violations (deterministic)"
        )
        return result

    # ================================================================
    #  BOUNDED TASK 7: describe_subtask (name composition)
    # ================================================================

    def describe_subtask(self, target: str, action: str, context: str = "") -> str:
        """
        Genera un nombre descriptivo para un subtask.

        100% determinístico. NUNCA llama al LLM.
        Mejora: Nombres consistentes y limpios.
        """
        safe_target = re.sub(r'[^a-z0-9_]', '_', target.lower()).strip('_')
        safe_action = re.sub(r'[^a-z0-9_]', '_', action.lower()).strip('_')

        # Limpiar underscores duplicados
        name = re.sub(r'_+', '_', f"{safe_action}_{safe_target}").strip('_')

        if not name or len(name) < 3:
            name = "unnamed_subtask"

        logger.debug(f"BoundedTasks.describe_subtask: {name} (deterministic)")
        return name

    # ================================================================
    #  INTERNAL HELPERS (deterministic only)
    # ================================================================

    def _deterministic_goal(self, text_lower: str) -> str:
        """Deterministic goal classification from text."""
        best_goal, best_score = "FEATURE_ADD", 0
        for goal, keywords in self.GOAL_KEYWORDS.items():
            score = sum(1 for kw in keywords if kw in text_lower)
            if score > best_score:
                best_score, best_goal = score, goal
        return best_goal
