import {
  Webhook,
  Cpu,
  Shield,
  Scale,
  Eye as EyeIcon,
  BookOpen,
  CreditCard,
  Brain,
  Users,
  LayoutDashboard,
  FileText,
  type LucideIcon,
} from "lucide-react";

// ═══════════════════════════════════════════════════════════════════════════════
// APIs DE ZENIC-AGENTS — Solo las APIs que pertenecen al proyecto
// ═══════════════════════════════════════════════════════════════════════════════

export interface ApiGroup {
  id: string;
  nombre: string;
  descripcion: string;
  basePath: string;
  endpoints: number;
  icon: LucideIcon;
  color: string;
  auth: string[];
  metodos: string[];
  rutas: string[];
}

export const ZENIC_API_GROUPS: ApiGroup[] = [
  {
    id: "mcp-gateway",
    nombre: "MCP Gateway",
    descripcion: "Ejecución de herramientas con pipeline de 7 pasos (resolución → auth → rate limit → RBAC → política → ejecución → auditoría Merkle)",
    basePath: "/api/mcp",
    endpoints: 7,
    icon: Webhook,
    color: "emerald",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST", "PUT", "DELETE"],
    rutas: [
      "GET /api/mcp/tools — Listar herramientas MCP",
      "POST /api/mcp/tools — Crear herramienta",
      "GET /api/mcp/servers — Listar servidores MCP",
      "POST /api/mcp/servers — Crear servidor",
      "POST /api/mcp/gateway — Ejecutar herramienta (veredicto: allow/deny/conditional)",
      "POST /api/mcp/gateway/approve — Aprobar ejecución pendiente",
      "POST /api/mcp/gateway/deny — Denegar ejecución",
    ],
  },
  {
    id: "mcp-protocol",
    nombre: "MCP Protocolo (JSON-RPC 2.0)",
    descripcion: "Capa de protocolo MCP con JSON-RPC 2.0 — initialize, tools/list, tools/call, tools/register",
    basePath: "/api/v1/mcp",
    endpoints: 4,
    icon: Cpu,
    color: "teal",
    auth: ["api_key", "bearer"],
    metodos: ["POST", "GET"],
    rutas: [
      "POST /api/v1/mcp/initialize — Handshake MCP (capacidades, versión)",
      "POST /api/v1/mcp/call — Gateway JSON-RPC completo (7 pasos observables)",
      "GET /api/v1/mcp/tools — Listar herramientas con agrupación",
      "POST /api/v1/mcp/tools/register — Registrar herramienta dinámica",
    ],
  },
  {
    id: "policy-engine",
    nombre: "Motor de Políticas",
    descripcion: "Motor declarativo de políticas con verificación Z3/AC3-CSP, composición, namespaces multi-tenant, simulaciones what-if",
    basePath: "/api/v1/policy-engine",
    endpoints: 21,
    icon: Shield,
    color: "amber",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST", "PUT", "DELETE"],
    rutas: [
      "POST /api/v1/policy-engine/verify — Verificación con solver de restricciones (Z3/AC3)",
      "GET /api/v1/policy-engine/composition — Listar conjuntos de políticas",
      "POST /api/v1/policy-engine/composition — Crear conjunto",
      "POST /api/v1/policy-engine/composition/[setId]/compose — Componer/merger",
      "GET /api/v1/policy-engine/conflicts — Detectar conflictos entre políticas",
      "POST /api/v1/policy-engine/conflicts/[id]/resolve — Resolver conflicto",
      "GET /api/v1/policy-engine/namespaces — Listar namespaces multi-tenant",
      "POST /api/v1/policy-engine/namespaces — Crear namespace",
      "POST /api/v1/policy-engine/namespaces/[id]/evaluate — Evaluar en contexto",
      "POST /api/v1/policy-engine/impact — Análisis de impacto (radio de explosión)",
      "GET /api/v1/policy-engine/templates — Listar plantillas parametrizadas",
      "POST /api/v1/policy-engine/templates/[id]/instantiate — Generar política",
      "POST /api/v1/policy-engine/simulations — Simulación what-if",
      "GET /api/v1/policy-engine/approvals — Solicitudes de aprobación (Draft→Review→Deploy)",
      "POST /api/v1/policy-engine/approvals/[id]/deploy — Desplegar política aprobada",
    ],
  },
  {
    id: "hitl",
    nombre: "HITL — Human-in-the-Loop",
    descripcion: "Sistema de aprobaciones humanas con delegación, escalamiento, undo, evidencia, SLA y coordinación multi-revisor",
    basePath: "/api/v1/hitl",
    endpoints: 24,
    icon: Scale,
    color: "rose",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST"],
    rutas: [
      "GET /api/v1/hitl — Listar solicitudes de aprobación",
      "POST /api/v1/hitl — Crear solicitud",
      "POST /api/v1/hitl/[id]/approve — Aprobar solicitud",
      "POST /api/v1/hitl/[id]/reject — Rechazar solicitud",
      "POST /api/v1/hitl/[id]/undo — Deshacer acción aprobada",
      "POST /api/v1/hitl/[id]/escalate — Escalar solicitud",
      "POST /api/v1/hitl/[id]/delegate — Delegar a otro revisor",
      "GET /api/v1/hitl/pending — Solicitudes pendientes",
      "GET /api/v1/hitl/evidence — Adjuntar evidencia",
      "POST /api/v1/hitl/expiry/check — Verificar expiraciones",
      "GET /api/v1/hitl/sla/[id] — Estado SLA",
      "POST /api/v1/hitl/coordinator/create — Coordinar aprobación multi-revisor",
    ],
  },
  {
    id: "observability",
    nombre: "Observabilidad",
    descripcion: "Trazas distribuidas (W3C), métricas de seguridad/negocio/resiliencia, exportación OpenTelemetry",
    basePath: "/api/v1/observability",
    endpoints: 9,
    icon: EyeIcon,
    color: "sky",
    auth: ["api_key", "bearer"],
    metodos: ["GET"],
    rutas: [
      "GET /api/v1/observability/traces — Consultar trazas distribuidas",
      "GET /api/v1/observability/traces/[id] — Traza con spans",
      "GET /api/v1/observability/spans — Consultar spans",
      "GET /api/v1/observability/metrics — Series de métricas",
      "GET /api/v1/observability/metrics/security — Métricas de seguridad",
      "GET /api/v1/observability/metrics/business — Métricas de negocio",
      "GET /api/v1/observability/metrics/resilience — Métricas de resiliencia",
      "GET /api/v1/observability/export/json — Exportar como JSON",
      "GET /api/v1/observability/export/otel — Exportar formato OpenTelemetry",
    ],
  },
  {
    id: "playbooks",
    nombre: "Playbooks Industriales",
    descripcion: "Playbooks por industria con ROI, certificación, onboarding, pricing y compliance",
    basePath: "/api/v1/playbooks",
    endpoints: 11,
    icon: BookOpen,
    color: "violet",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST"],
    rutas: [
      "GET /api/v1/playbooks — Listar playbooks",
      "POST /api/v1/playbooks/activate — Activar playbook para tenant",
      "GET /api/v1/playbooks/roi — Cálculos ROI",
      "GET /api/v1/playbooks/compliance — Mapeo de cumplimiento",
      "POST /api/v1/playbooks/certification — Certificar playbook",
      "POST /api/v1/playbooks/evaluate — Evaluar playbook",
      "GET /api/v1/playbooks/pricing — Información de precios",
      "POST /api/v1/playbooks/onboarding — Sesión de onboarding",
    ],
  },
  {
    id: "subscription",
    nombre: "Suscripción & Pagos",
    descripcion: "Gestión de suscripciones, pagos USDT/TRC20, saga de registro, tiers y add-ons",
    basePath: "/api/v1/subscription",
    endpoints: 15,
    icon: CreditCard,
    color: "orange",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST"],
    rutas: [
      "GET /api/v1/subscription — Suscripción del tenant",
      "POST /api/v1/subscription/signup — Registrar suscripción",
      "POST /api/v1/subscription/trial — Iniciar prueba gratuita",
      "POST /api/v1/subscription/cancel — Cancelar suscripción",
      "GET /api/v1/subscription/features — Features por tier",
      "GET /api/v1/subscription/usage — Uso vs límites actuales",
      "GET /api/v1/subscription/tiers — Tiers disponibles",
      "POST /api/v1/subscription/payment/confirm — Confirmar pago crypto (TRC20)",
      "POST /api/v1/subscription/payment/verify — Verificar pago on-chain",
      "GET /api/v1/subscription/saga/status — Estado de saga",
    ],
  },
  {
    id: "memory-chip",
    nombre: "Chip de Memoria",
    descripcion: "Sistema de memoria adaptativa con ontología, mappings, aprobaciones y ciclo de vida",
    basePath: "/api/v1/memory-chip",
    endpoints: 9,
    icon: Brain,
    color: "pink",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST"],
    rutas: [
      "GET /api/v1/memory-chip/stats — Estadísticas de memoria",
      "POST /api/v1/memory-chip/lifecycle/start — Iniciar episodio",
      "POST /api/v1/memory-chip/lifecycle/advance — Avanzar estado",
      "POST /api/v1/memory-chip/ontology/search — Buscar ontología",
      "POST /api/v1/memory-chip/adapt — Activar adaptación",
      "POST /api/v1/memory-chip/lookup — Consultar mapping",
      "GET /api/v1/memory-chip/mappings — Listar mappings",
      "POST /api/v1/memory-chip/approve — Aprobar mapping pendiente",
    ],
  },
  {
    id: "rbac",
    nombre: "RBAC — Control de Acceso",
    descripcion: "Gestión de roles, permisos, asignación y verificación de acceso basado en roles",
    basePath: "/api/rbac",
    endpoints: 6,
    icon: Users,
    color: "slate",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST", "PUT", "DELETE"],
    rutas: [
      "GET /api/rbac/roles — Listar roles",
      "POST /api/rbac/roles — Crear rol",
      "GET /api/rbac/permissions — Listar permisos",
      "POST /api/rbac/assign — Asignar rol a usuario",
      "POST /api/rbac/revoke — Revocar rol",
      "POST /api/rbac/check — Verificar permiso",
    ],
  },
  {
    id: "dashboard",
    nombre: "Dashboard",
    descripcion: "Métricas, actividad, propuestas, alertas SNA, ledger, pipeline, ROI y nichos",
    basePath: "/api/dashboard",
    endpoints: 14,
    icon: LayoutDashboard,
    color: "gray",
    auth: ["api_key", "bearer"],
    metodos: ["GET"],
    rutas: [
      "GET /api/dashboard/metrics — 14 KPIs del sistema",
      "GET /api/dashboard/activity — Últimas 20 entradas de auditoría",
      "GET /api/dashboard/memory-proposals — Propuestas HITL pendientes",
      "GET /api/dashboard/sna-alerts — Alertas SNA (24h)",
      "GET /api/dashboard/ledger — Cadena Merkle de auditoría",
      "GET /api/dashboard/roi — Métricas ROI",
      "GET /api/dashboard/niches — Catálogo de nichos",
      "GET /api/dashboard/pipeline-status — Estado del pipeline",
      "GET /api/dashboard/defense-layers — Estado de capas de defensa",
    ],
  },
  {
    id: "policies",
    nombre: "Políticas Declarativas",
    descripcion: "CRUD de políticas declarativas, versionado, evaluación, diff, tests y hot-reload",
    basePath: "/api/v1/policies",
    endpoints: 9,
    icon: FileText,
    color: "indigo",
    auth: ["api_key", "bearer"],
    metodos: ["GET", "POST", "PUT", "DELETE"],
    rutas: [
      "GET /api/v1/policies — Listar políticas",
      "POST /api/v1/policies — Crear política (JSON/YAML)",
      "GET /api/v1/policies/versions — Versiones de políticas",
      "GET /api/v1/policies/compliance — Reporte de cumplimiento",
      "POST /api/v1/policies/evaluate — Evaluar solicitud contra políticas",
      "POST /api/v1/policies/diff — Diff entre versiones",
      "POST /api/v1/policies/tests — Ejecutar suite de tests",
      "POST /api/v1/policies/hot-reload — Recargar políticas en caliente",
    ],
  },
];

// ─── Servicios Externos de Conexión (Agentes) ────────────────────────────────

export const EXTERNAL_SERVICES = [
  { id: "jira", nombre: "Jira", descripcion: "REST API v2 — Crear issues, transiciones, búsqueda JQL", campos: ["JIRA_BASE_URL", "JIRA_EMAIL", "JIRA_API_TOKEN"], authType: "basic_auth", icon: "📋" },
  { id: "servicenow", nombre: "ServiceNow", descripcion: "Table API — Incidentes, cambios, solicitudes", campos: ["SERVICENOW_INSTANCE_URL", "SERVICENOW_USERNAME", "SERVICENOW_PASSWORD"], authType: "basic_auth", icon: "🔧" },
  { id: "teams", nombre: "Microsoft Teams", descripcion: "Incoming Webhooks + Bot Framework", campos: ["TEAMS_WEBHOOK_URL", "TEAMS_BOT_TOKEN"], authType: "bearer", icon: "💬" },
  { id: "slack", nombre: "Slack", descripcion: "Web API + Socket Mode", campos: ["SLACK_BOT_TOKEN", "SLACK_APP_TOKEN", "SLACK_SIGNING_SECRET"], authType: "bearer", icon: "📱" },
  { id: "whatsapp", nombre: "WhatsApp Cloud", descripcion: "Meta Graph API v18.0", campos: ["WHATSAPP_ACCESS_TOKEN", "WHATSAPP_PHONE_NUMBER_ID", "WHATSAPP_VERIFY_TOKEN"], authType: "bearer", icon: "📲" },
  { id: "twilio", nombre: "Twilio SMS", descripcion: "REST API — Envío de SMS", campos: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"], authType: "api_key", icon: "📞" },
  { id: "email", nombre: "Email (SMTP/Graph)", descripcion: "SMTP o Microsoft Graph API", campos: ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD", "MSGRAPH_CLIENT_ID", "MSGRAPH_CLIENT_SECRET"], authType: "basic_auth", icon: "📧" },
  { id: "custom", nombre: "Servicio Personalizado", descripcion: "Conexión genérica HTTP/HTTPS", campos: ["ENDPOINT_URL", "AUTH_CREDENTIAL"], authType: "custom", icon: "🔌" },
];

export const CREDENTIAL_TYPES = [
  { value: "api_key", label: "API Key" },
  { value: "bearer", label: "Bearer Token" },
  { value: "oauth2", label: "OAuth 2.0" },
  { value: "basic_auth", label: "Autenticación Básica" },
  { value: "custom", label: "Personalizado" },
];

export const PROTOCOLS = [
  { value: "http", label: "HTTP" },
  { value: "websocket", label: "WebSocket" },
  { value: "grpc", label: "gRPC" },
  { value: "stdio", label: "stdio" },
];

export const AUTH_TYPES = [
  { value: "none", label: "Ninguna" },
  { value: "api_key", label: "API Key" },
  { value: "bearer", label: "Bearer Token" },
  { value: "oauth2", label: "OAuth 2.0" },
  { value: "mtls", label: "mTLS" },
];
