"""
DeterministicPipeline - Pipeline que hace TODAS las tareas sin IA.

Reemplaza las 7 tareas bounded de MiniAIEngine con versiones
puramente determinísticas que son más rápidas y más confiables.

Tareas reemplazadas:
  1. classify_intent()    → Keyword scoring + evidencia
  2. extract_entities()   → Regex extraction + patrones
  3. suggest_pattern()    → Lookup table + heuristicas
  4. fill_template_gaps() → Context mapping + defaults
  5. generate_pattern()   → Template library + composición
  6. explain_violation()  → Formateo automático + catálogo
  7. describe_subtask()   → Composición automática de nombre

Ventajas sobre la versión con IA:
  - 0ms de latencia LLM (antes 3-8s por llamada)
  - 0% de alucinaciones
  - 0% de parsing errors (no depende de output de IA)
  - Determinístico: mismo input → mismo output, siempre
  - Funciona sin GPU, sin modelo, sin dependencias externas
"""

import re
import os
import json
import logging
from typing import Dict, Any, List, Optional
from ..types import DeterministicResult, Evidence, EvidenceType, Verdict


logger = logging.getLogger(__name__)

# === Tabla de extensión a lenguaje ===
EXT_LANG_MAP = {
    ".py": "python", ".kt": "kotlin", ".go": "go",
    ".js": "javascript", ".ts": "typescript", ".java": "java",
    ".rs": "rust", ".rb": "ruby", ".cpp": "cpp", ".c": "c",
    ".h": "c", ".hpp": "cpp", ".swift": "swift", ".scala": "scala",
}

# === Tabla de patrones de código por lenguaje ===
PATTERN_LIBRARY = {
    "python": {
        "async_await": "async def {name}({params}):\n    result = await {operation}({params})\n    return result\n",
        "validator": "def {name}(data: dict) -> bool:\n    required = {required_fields}\n    return all(k in data for k in required)\n",
        "repository": "class {class_name}:\n    def __init__(self, db):\n        self.db = db\n    def get_by_id(self, id: str):\n        return self.db.query(id)\n",
        "factory": "def create_{name}(type_: str):\n    handlers = {handler_map}\n    return handlers.get(type_, DefaultHandler)\n",
        "middleware": "def {name}(func):\n    def wrapper(*args, **kwargs):\n        pre_process(*args)\n        result = func(*args, **kwargs)\n        post_process(result)\n        return result\n    return wrapper\n",
        "observer": "class {class_name}:\n    def __init__(self):\n        self._observers = []\n    def subscribe(self, observer):\n        self._observers.append(observer)\n    def notify(self, event):\n        for obs in self._observers:\n            obs.on_event(event)\n",
        "security": "import hashlib, secrets\n\ndef hash_password(password: str) -> str:\n    salt = secrets.token_hex(16)\n    return hashlib.sha256((salt + password).encode()).hexdigest()\n",
        "cache": "from functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef {name}(key):\n    return expensive_lookup(key)\n",
        "singleton": "class {class_name}:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n",
        "default": "def {name}(data):\n    \"\"\"Generated by ZENIC-AGENTS v1\"\"\"\n    return data\n",
    },
    "javascript": {
        "async_await": "async function {name}({params}) {\n    const result = await {operation}({params});\n    return result;\n}\n",
        "validator": "function {name}(data) {\n    const required = {required_fields};\n    return required.every(k => k in data);\n}\n",
        "default": "function {name}(data) {\n    return data;\n}\n",
    },
    "typescript": {
        "default": "function {name}(data: any): any {\n    return data;\n}\n",
    },
}

# === Catálogo de violaciones con explicaciones ===
VIOLATION_CATALOG = {
    "exec_call": "Use of exec() allows arbitrary code execution, which is a critical security risk.",
    "eval_call": "Use of eval() allows arbitrary code execution, which is a critical security risk.",
    "import_call": "Dynamic import via __import__() can load untrusted modules at runtime.",
    "os_system": "os.system() executes shell commands, vulnerable to injection attacks.",
    "subprocess_call": "subprocess calls can execute arbitrary system commands.",
    "pickle_load": "pickle.loads() can deserialize malicious objects leading to RCE.",
    "yaml_unsafe": "yaml.load() without SafeLoader can execute arbitrary Python code.",
    "sensitive_file": "Access to sensitive system files (/etc, /proc, /sys) detected.",
    "rm_rf": "Dangerous rm -rf command detected, can destroy entire filesystems.",
    "socket_raw": "Raw socket creation detected, may indicate network-level exploits.",
    "null_pointer": "Potential null/None dereference detected.",
    "type_mismatch": "Type mismatch detected in function call.",
    "unreachable": "Unreachable code detected after return statement.",
    "unused_import": "Unused import detected.",
}

# === Mapa de heuristicas para sugerir patrones ===
PATTERN_HEURISTICS = [
    (["async", "await", "coroutine", "asincrono"], "async_await"),
    (["validate", "validar", "check", "verify", "verificar"], "validator"),
    (["repository", "repo", "database", "db", "base de datos"], "repository"),
    (["factory", "create", "creator", "fabrica"], "factory"),
    (["middleware", "interceptor", "pipeline"], "middleware"),
    (["observer", "subscribe", "event", "listen", "escuchar"], "observer"),
    (["security", "auth", "login", "token", "seguridad"], "security"),
    (["cache", "memoize", "store", "cachear"], "cache"),
    (["singleton", "single", "unique", "unico"], "singleton"),
    (["test", "testing", "prueba", "spec"], "default"),
]


