"""
TestGenerator — Code Generation Mixin.

Generates pytest test file content: headers, imports, fixtures,
class tests, method tests, and function tests.
"""

import logging
from typing import Any, Dict, List

from ._helpers import generate_test_args, generate_edge_case_args

logger = logging.getLogger(__name__)


class CodeGenMixin:
    """Mixin providing code generation methods for TestGenerator."""

    def _generate_header(self, module_name: str, project_name: str) -> str:
        """Generate test file header."""
        return f'"""Auto-generated tests for {module_name}.\nGenerated by ZENIC-AGENTS TestGenerator (M9).\nProject: {project_name}\n"""'

    def _generate_imports(self, module_name: str, classes: List[Dict]) -> str:
        """Generate import statements."""
        lines = [
            "import pytest",
            "import sqlite3",
            "import os",
            "import tempfile",
            "from unittest.mock import Mock, patch, AsyncMock",
        ]

        # Import the module under test
        lines.append(f"import {module_name}")

        # Import specific classes
        for cls in classes:
            lines.append(f"from {module_name} import {cls['name']}")

        return '\n'.join(lines)

    def _generate_fixtures(self, classes: List[Dict]) -> str:
        """Generate pytest fixtures for testing."""
        lines = [
            "",
            "",
            "# ── Fixtures ──",
            "",
            "@pytest.fixture",
            "def db_connection():",
            '    """In-memory SQLite database for testing."""',
            "    conn = sqlite3.connect(':memory:')",
            "    conn.row_factory = sqlite3.Row",
            "    yield conn",
            "    conn.close()",
            "",
        ]

        # Generate fixture for each class
        for cls in classes:
            cls_name = cls["name"]
            fixture_name = cls_name.lower()

            if cls["type"] == "crud":
                lines.extend([
                    f"@pytest.fixture",
                    f"def {fixture_name}(db_connection):",
                    f'    """Create {cls_name} instance with test database."""',
                    f"    with patch.object({cls_name}, '__init__', lambda self, **kw: None):",
                    f"        instance = {cls_name}.__new__({cls_name})",
                    f"        instance._db_path = ':memory:'",
                    f"        instance._conn = db_connection",
                    f"    return instance",
                    "",
                ])
            elif cls["type"] == "auth":
                lines.extend([
                    f"@pytest.fixture",
                    f"def {fixture_name}():",
                    f'    """Create {cls_name} instance for testing."""',
                    f"    instance = {cls_name}(secret_key='test-secret-key-for-testing', token_expire_minutes=5)",
                    f"    return instance",
                    "",
                ])
            else:
                lines.extend([
                    f"@pytest.fixture",
                    f"def {fixture_name}():",
                    f'    """Create {cls_name} instance for testing."""',
                    f"    try:",
                    f"        return {cls_name}()",
                    f"    except TypeError:",
                    f"        return {cls_name}.__new__({cls_name})",
                    "",
                ])

        return '\n'.join(lines)

    def _generate_class_tests(self, cls_info: Dict, module_name: str) -> str:
        """Generate test methods for a class."""
        cls_name = cls_info["name"]
        fixture_name = cls_name.lower()
        lines = [
            f"",
            f"# ── Tests for {cls_name} ──",
            f"",
            f"class Test{cls_name}:",
            f'    """Tests for {cls_name} ({cls_info["type"]})."""',
            "",
        ]

        # Test instantiation
        lines.extend([
            f"    def test_instantiation(self, {fixture_name}):",
            f'        """Test that {cls_name} can be instantiated."""',
            f"        assert {fixture_name} is not None",
            f"        assert isinstance({fixture_name}, {cls_name})",
            "",
        ])

        # Generate tests for each public method
        for method in cls_info["methods"]:
            if method["is_private"]:
                continue  # Skip private methods

            method_tests = self._generate_method_tests(
                cls_name, fixture_name, method
            )
            lines.extend(method_tests)

        return '\n'.join(lines)

    def _generate_method_tests(self, cls_name: str, fixture_name: str,
                                method: Dict) -> List[str]:
        """Generate test methods for a single class method."""
        method_name = method["name"]
        args = method["args"]
        is_async = method["is_async"]
        lines = []

        # Test 1: Method exists
        lines.extend([
            f"    def test_{method_name}_exists(self, {fixture_name}):",
            f'        """Test that {cls_name}.{method_name} exists."""',
            f"        assert hasattr({fixture_name}, '{method_name}')",
            f"        assert callable(getattr({fixture_name}, '{method_name}'))",
            "",
        ])

        # Test 2: Method call with valid arguments
        test_args = generate_test_args(args, method_name)
        async_prefix = "async " if is_async else ""
        await_prefix = "await " if is_async else ""

        lines.extend([
            f"    {async_prefix}def test_{method_name}_call(self, {fixture_name}):",
            f'        """Test calling {method_name} with valid arguments."""',
            f"        result = {await_prefix}{fixture_name}.{method_name}({test_args})",
            f"        assert result is not None",
            "",
        ])

        # Test 3: Method handles edge cases
        if args:
            edge_args = generate_edge_case_args(args)
            lines.extend([
                f"    def test_{method_name}_edge_cases(self, {fixture_name}):",
                f'        """Test {method_name} with edge case inputs."""',
                f"        try:",
                f"            result = {fixture_name}.{method_name}({edge_args})",
                f"            # Method should handle edge cases gracefully",
                f"            assert result is not None or result is None",
                f"        except (ValueError, TypeError):",
                f"            pass  # Expected for invalid inputs",
                "",
            ])

        return lines

    def _generate_function_tests(self, fn_info: Dict, module_name: str) -> str:
        """Generate test functions for standalone functions."""
        fn_name = fn_info["name"]
        args = fn_info["args"]
        is_async = fn_info["is_async"]

        test_args = generate_test_args(args, fn_name)
        async_prefix = "async " if is_async else ""
        await_prefix = "await " if is_async else ""

        lines = [
            f"",
            f"# ── Tests for {fn_name} ──",
            f"",
            f"def test_{fn_name}_exists():",
            f'    """Test that {fn_name} exists."""',
            f"    assert hasattr({module_name}, '{fn_name}')",
            f"    assert callable({module_name}.{fn_name})",
            "",
            f"{async_prefix}def test_{fn_name}_call():",
            f'    """Test calling {fn_name} with valid arguments."""',
            f"    result = {await_prefix}{module_name}.{fn_name}({test_args})",
            f"    assert result is not None",
            "",
        ]

        return '\n'.join(lines)
