"""
TestGenerator — Helper utilities and constants.

Static helper methods for type detection, test argument generation,
and error/fallback test generation.
"""

import ast
import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# Type mapping for test fixtures
TYPE_FIXTURES: Dict[str, str] = {
    "str": '""',
    "int": "1",
    "float": "1.0",
    "bool": "True",
    "list": "[]",
    "dict": "{}",
    "Optional[str]": "None",
    "Optional[int]": "None",
    "Any": "None",
}


def detect_class_type(class_name: str, methods: List[Dict]) -> str:
    """Detect what type of class this is based on name and methods."""
    name_lower = class_name.lower()
    method_names = [m["name"].lower() for m in methods]

    if any(kw in name_lower for kw in ["crud", "service", "repository"]):
        return "crud"
    if any(kw in name_lower for kw in ["auth", "security", "jwt"]):
        return "auth"
    if any(kw in name_lower for kw in ["client", "http", "api"]):
        return "client"
    if any(kw in name_lower for kw in ["analytics", "report"]):
        return "analytics"
    if any(kw in name_lower for kw in ["notifier", "notification"]):
        return "notification"
    # Detect by methods
    if "create" in method_names and "read" in method_names:
        return "crud"
    if "hash_password" in method_names or "verify_password" in method_names:
        return "auth"
    return "generic"


def generate_test_args(args: List[Dict], method_name: str = "") -> str:
    """Generate test argument values."""
    if not args:
        return ""

    parts = []
    for arg in args:
        name = arg["name"]
        annotation = arg.get("annotation", "")

        if "data" in name or "payload" in name:
            parts.append(f"{name}={{'name': 'test', 'status': 'active'}}")
        elif "id" in name:
            parts.append(f"{name}=1")
        elif "query" in name or "search" in name:
            parts.append(f"{name}='test'")
        elif "password" in name:
            parts.append(f"{name}='test_password_123'")
        elif "token" in name:
            parts.append(f"{name}='test_token'")
        elif "email" in name:
            parts.append(f"{name}='test@example.com'")
        elif "username" in name:
            parts.append(f"{name}='testuser'")
        elif "limit" in name:
            parts.append(f"{name}=10")
        elif "offset" in name:
            parts.append(f"{name}=0")
        elif "int" in annotation.lower():
            parts.append(f"{name}=1")
        elif "float" in annotation.lower() or "decimal" in annotation.lower():
            parts.append(f"{name}=1.0")
        elif "bool" in annotation.lower():
            parts.append(f"{name}=True")
        elif "list" in annotation.lower():
            parts.append(f"{name}=[]")
        elif "dict" in annotation.lower():
            parts.append(f"{name}={{}}")
        else:
            parts.append(f"{name}='test_value'")

    return ", ".join(parts)


def generate_edge_case_args(args: List[Dict]) -> str:
    """Generate edge case argument values."""
    if not args:
        return ""

    parts = []
    for arg in args:
        name = arg["name"]
        if "id" in name:
            parts.append(f"{name}=0")
        elif "data" in name or "payload" in name:
            parts.append(f"{name}={{}}")
        else:
            parts.append(f"{name}=None")

    return ", ".join(parts)


def annotation_to_str(annotation: Any) -> str:
    """Convert AST annotation to string."""
    if annotation is None:
        return ""
    try:
        return ast.dump(annotation)
    except Exception:
        return ""


def generate_syntax_error_tests(module_name: str, error: SyntaxError) -> str:
    """Generate tests when the source has syntax errors."""
    return f'''"""Auto-generated tests for {module_name}.
Generated by ZENIC-AGENTS TestGenerator (M9).

WARNING: Source code has syntax errors. Only import test generated.
"""

import pytest


def test_module_import():
    """Test that {module_name} can be imported despite syntax errors."""
    try:
        import {module_name}
        assert {module_name} is not None
    except SyntaxError as e:
        pytest.skip(f"Module has syntax error: {{e}}")
'''


def generate_minimal_tests(module_name: str) -> str:
    """Generate minimal tests when no classes/functions found."""
    return f'''"""Auto-generated tests for {module_name}.
Generated by ZENIC-AGENTS TestGenerator (M9).
No testable classes/functions found in source.
"""

import pytest


def test_module_import():
    """Test that {module_name} can be imported."""
    import {module_name}
    assert {module_name} is not None
'''
