// ─── Seed Data — Content Definitions ───────────────────────────────────
// Tool defs, HITL data, and audit entries.
// Extracted from _seed-data.ts to stay under 400 lines.

export function getToolDefs(serverIds: string[]): Array<{
  name: string;
  displayName: string;
  description: string;
  category: string;
  version: string;
  icon: string;
  endpoint: string;
  method: string;
  inputSchema: string;
  timeout: number;
  retries: number;
  rateLimit: number;
  riskLevel: string;
  status: string;
  requiresApproval: boolean;
  tags: string;
  metadata: string;
  serverId: string;
}> {
  return [
    {
      name: "weather_lookup",
      displayName: "Weather Lookup",
      description: "Retrieve current weather conditions and forecasts for any global location",
      category: "external",
      version: "2.3.0",
      icon: "Cloud",
      endpoint: "/api/tools/weather",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { location: { type: "string" }, units: { type: "string", enum: ["celsius", "fahrenheit"] } }, required: ["location"] }),
      timeout: 10000,
      retries: 2,
      rateLimit: 60,
      riskLevel: "low",
      status: "active",
      requiresApproval: false,
      tags: JSON.stringify(["weather", "external", "api"]),
      metadata: JSON.stringify({ provider: "OpenWeatherMap", cacheTTL: 300 }),
      serverId: serverIds[0],
    },
    {
      name: "db_query",
      displayName: "Database Query",
      description: "Execute read-only SQL queries against authorized database connections with result pagination",
      category: "data",
      version: "1.8.2",
      icon: "Database",
      endpoint: "/api/tools/db/query",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { query: { type: "string" }, connectionId: { type: "string" }, limit: { type: "number", default: 100 } }, required: ["query", "connectionId"] }),
      timeout: 30000,
      retries: 1,
      rateLimit: 30,
      riskLevel: "medium",
      status: "active",
      requiresApproval: true,
      tags: JSON.stringify(["database", "sql", "read-only"]),
      metadata: JSON.stringify({ supportedDbs: ["postgresql", "mysql", "sqlite"] }),
      serverId: serverIds[0],
    },
    {
      name: "file_read",
      displayName: "File Reader",
      description: "Read file contents from authorized storage paths with format detection and encoding support",
      category: "storage",
      version: "1.5.1",
      icon: "FileText",
      endpoint: "/api/tools/file/read",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { path: { type: "string" }, encoding: { type: "string", default: "utf-8" } }, required: ["path"] }),
      timeout: 10000,
      retries: 2,
      rateLimit: 100,
      riskLevel: "medium",
      status: "active",
      requiresApproval: false,
      tags: JSON.stringify(["file", "storage", "read"]),
      metadata: JSON.stringify({ maxFileSize: "10MB", supportedEncodings: ["utf-8", "ascii", "base64"] }),
      serverId: serverIds[2],
    },
    {
      name: "email_send",
      displayName: "Email Sender",
      description: "Send templated emails to internal and external recipients with delivery tracking",
      category: "communication",
      version: "3.1.0",
      icon: "Mail",
      endpoint: "/api/tools/email/send",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { to: { type: "array", items: { type: "string" } }, subject: { type: "string" }, template: { type: "string" } }, required: ["to", "subject"] }),
      timeout: 15000,
      retries: 3,
      rateLimit: 20,
      riskLevel: "high",
      status: "active",
      requiresApproval: true,
      tags: JSON.stringify(["email", "communication", "notifications"]),
      metadata: JSON.stringify({ provider: "SendGrid", trackingEnabled: true }),
      serverId: serverIds[3],
    },
    {
      name: "compute_task",
      displayName: "Compute Task",
      description: "Submit and manage compute tasks including data processing, ML inference, and batch operations",
      category: "compute",
      version: "2.0.0",
      icon: "Cpu",
      endpoint: "/api/tools/compute",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { taskType: { type: "string", enum: ["data_processing", "ml_inference", "batch"] }, payload: { type: "object" } }, required: ["taskType", "payload"] }),
      timeout: 120000,
      retries: 1,
      rateLimit: 10,
      riskLevel: "high",
      status: "active",
      requiresApproval: true,
      tags: JSON.stringify(["compute", "ml", "processing"]),
      metadata: JSON.stringify({ maxMemory: "4GB", gpuAvailable: true }),
      serverId: serverIds[4],
    },
    {
      name: "security_scan",
      displayName: "Security Scanner",
      description: "Run vulnerability and compliance scans on target resources with detailed finding reports",
      category: "security",
      version: "1.2.0",
      icon: "Shield",
      endpoint: "/api/tools/security/scan",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { target: { type: "string" }, scanType: { type: "string", enum: ["vulnerability", "compliance", "full"] } }, required: ["target", "scanType"] }),
      timeout: 60000,
      retries: 1,
      rateLimit: 5,
      riskLevel: "critical",
      status: "active",
      requiresApproval: true,
      tags: JSON.stringify(["security", "scanning", "compliance"]),
      metadata: JSON.stringify({ scanEngines: ["nmap", "owasp-zap", "trivy"] }),
      serverId: serverIds[0],
    },
    {
      name: "metrics_collect",
      displayName: "Metrics Collector",
      description: "Collect and aggregate system metrics from monitoring endpoints with customizable time ranges",
      category: "monitoring",
      version: "1.4.0",
      icon: "Activity",
      endpoint: "/api/tools/metrics/collect",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { source: { type: "string" }, timeRange: { type: "string" }, granularity: { type: "string", default: "5m" } }, required: ["source", "timeRange"] }),
      timeout: 20000,
      retries: 2,
      rateLimit: 50,
      riskLevel: "low",
      status: "active",
      requiresApproval: false,
      tags: JSON.stringify(["monitoring", "metrics", "observability"]),
      metadata: JSON.stringify({ backends: ["prometheus", "grafana", "datadog"] }),
      serverId: serverIds[1],
    },
    {
      name: "webhook_dispatch",
      displayName: "Webhook Dispatcher",
      description: "Dispatch webhook events to registered endpoints with retry logic and delivery confirmation",
      category: "communication",
      version: "2.2.1",
      icon: "Webhook",
      endpoint: "/api/tools/webhook/dispatch",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { url: { type: "string" }, event: { type: "string" }, payload: { type: "object" } }, required: ["url", "event", "payload"] }),
      timeout: 10000,
      retries: 3,
      rateLimit: 100,
      riskLevel: "medium",
      status: "active",
      requiresApproval: false,
      tags: JSON.stringify(["webhook", "integration", "events"]),
      metadata: JSON.stringify({ maxRetries: 5, retryBackoff: "exponential" }),
      serverId: serverIds[0],
    },
    {
      name: "inventory_check",
      displayName: "Inventory Checker",
      description: "Check real-time inventory levels across warehouses and trigger restock alerts when thresholds are breached",
      category: "data",
      version: "1.1.0",
      icon: "Package",
      endpoint: "/api/tools/inventory/check",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { sku: { type: "string" }, warehouse: { type: "string" } }, required: ["sku"] }),
      timeout: 8000,
      retries: 2,
      rateLimit: 80,
      riskLevel: "low",
      status: "active",
      requiresApproval: false,
      tags: JSON.stringify(["inventory", "warehouse", "data"]),
      metadata: JSON.stringify({ realtimeSync: true, alertThreshold: 5 }),
      serverId: serverIds[2],
    },
    {
      name: "schema_mapper",
      displayName: "Schema Mapper",
      description: "Map and transform data schemas between systems with drift detection and auto-mitigation proposals",
      category: "data",
      version: "1.0.0",
      icon: "GitBranch",
      endpoint: "/api/tools/schema/mapper",
      method: "POST",
      inputSchema: JSON.stringify({ type: "object", properties: { sourceSchema: { type: "string" }, targetSchema: { type: "string" }, autoApply: { type: "boolean", default: false } }, required: ["sourceSchema", "targetSchema"] }),
      timeout: 15000,
      retries: 1,
      rateLimit: 20,
      riskLevel: "medium",
      status: "testing",
      requiresApproval: true,
      tags: JSON.stringify(["schema", "mapping", "drift-detection"]),
      metadata: JSON.stringify({ driftDetection: true, autoPropose: true }),
      serverId: serverIds[2],
    },
  ];
}

export function getHitlData(adminUserId: string): Array<Record<string, unknown>> {
  return [
    {
      requestId: "mp-001",
      title: "Schema Drift: Column 'monto_neto' missing",
      description: "Map 'monto_neto' to 'subtotal_neto' — detected drift in ERP→Analytics schema pipeline",
      type: "action_approval",
      status: "pending",
      priority: "medium",
      requesterId: adminUserId,
      requesterName: "Memory Engine",
      targetResource: "schema_mapping",
      targetAction: "schema_drift",
      actionPayload: JSON.stringify({ source: "monto_neto", target: "subtotal_neto", confidence: 0.92 }),
      undoPayload: JSON.stringify({ revertMapping: true }),
      isReversible: true,
      approvalPolicy: JSON.stringify({ quorum: 1, autoApprove: false }),
      tags: JSON.stringify(["memory", "schema", "drift"]),
      metadata: JSON.stringify({ llmVerdict: true, engine: "memory-chip", driftType: "column_missing" }),
    },
    {
      requestId: "mp-002",
      title: "Intent Routing: 'consulta factura' → invoice_lookup",
      description: "Route 'consulta factura' intent to the invoice_lookup tool instead of db_query based on usage pattern analysis",
      type: "action_approval",
      status: "pending",
      priority: "high",
      requesterId: adminUserId,
      requesterName: "Memory Engine",
      targetResource: "intent_routing",
      targetAction: "intent_reroute",
      actionPayload: JSON.stringify({ intent: "consulta factura", currentTarget: "db_query", proposedTarget: "invoice_lookup", sampleSize: 150 }),
      undoPayload: JSON.stringify({ revertRouting: true }),
      isReversible: true,
      approvalPolicy: JSON.stringify({ quorum: 1, autoApprove: false }),
      tags: JSON.stringify(["memory", "intent", "routing"]),
      metadata: JSON.stringify({ llmVerdict: true, engine: "memory-chip", confidence: 0.88 }),
    },
    {
      requestId: "mp-003",
      title: "Policy Refinement: Relax email_send rate limit",
      description: "Increase email_send rate limit from 20/min to 35/min for operator role based on zero-abuse history (90d window)",
      type: "policy_change",
      status: "pending",
      priority: "low",
      requesterId: adminUserId,
      requesterName: "Memory Engine",
      targetResource: "access_policy",
      targetAction: "policy_refinement",
      actionPayload: JSON.stringify({ policyName: "rate-limit-operators", field: "quota.maxCalls", currentValue: 50, proposedValue: 80 }),
      undoPayload: JSON.stringify({ revertPolicy: true }),
      isReversible: true,
      approvalPolicy: JSON.stringify({ quorum: 2, autoApprove: false }),
      tags: JSON.stringify(["memory", "policy", "refinement"]),
      metadata: JSON.stringify({ llmVerdict: false, engine: "memory-chip", reasoning: "Zero abuse in 90d but needs dual approval" }),
    },
    {
      requestId: "mp-004",
      title: "Schema Drift: New table 'credit_notes' detected",
      description: "Auto-register 'credit_notes' table in the data catalog and map to existing invoice schema with credit_type discriminator",
      type: "action_approval",
      status: "pending",
      priority: "medium",
      requesterId: adminUserId,
      requesterName: "Memory Engine",
      targetResource: "schema_mapping",
      targetAction: "schema_drift",
      actionPayload: JSON.stringify({ table: "credit_notes", discriminator: "credit_type", parentSchema: "invoice" }),
      undoPayload: JSON.stringify({ unregisterTable: "credit_notes" }),
      isReversible: true,
      approvalPolicy: JSON.stringify({ quorum: 1, autoApprove: false }),
      tags: JSON.stringify(["memory", "schema", "drift"]),
      metadata: JSON.stringify({ llmVerdict: true, engine: "memory-chip", driftType: "table_added" }),
    },
    {
      requestId: "mp-005",
      title: "Intent Routing: 'estado pedido' → order_tracker",
      description: "Create new intent mapping 'estado pedido' → order_tracker tool (currently unhandled, 47 missed requests in 7 days)",
      type: "action_approval",
      status: "pending",
      priority: "high",
      requesterId: adminUserId,
      requesterName: "Memory Engine",
      targetResource: "intent_routing",
      targetAction: "intent_create",
      actionPayload: JSON.stringify({ intent: "estado pedido", proposedTarget: "order_tracker", missedRequests: 47, period: "7d" }),
      undoPayload: JSON.stringify({ removeIntent: "estado pedido" }),
      isReversible: true,
      approvalPolicy: JSON.stringify({ quorum: 1, autoApprove: false }),
      tags: JSON.stringify(["memory", "intent", "routing"]),
      metadata: JSON.stringify({ llmVerdict: true, engine: "memory-chip", confidence: 0.95 }),
    },
  ];
}

export function getAuditEntries(adminUserId: string): Array<Record<string, unknown>> {
  return [
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "weather_lookup", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "weather_lookup", verdict: "allow", duration: 450 }), tags: JSON.stringify(["execution"]), hoursAgo: 0.5 },
    { actorId: "system", actorType: "system", action: "policy.evaluate", resource: "policy", resourceName: "business-hours-only", severity: "info", outcome: "success", details: JSON.stringify({ policyName: "business-hours-only", verdict: "allow" }), tags: JSON.stringify(["policy"]), hoursAgo: 1 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "db_query", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "db_query", verdict: "allow", duration: 1200 }), tags: JSON.stringify(["execution"]), hoursAgo: 1.5 },
    { actorId: "system", actorType: "system", action: "policy.evaluate", resource: "policy", resourceName: "deny-external-after-hours", severity: "warn", outcome: "denied", details: JSON.stringify({ policyName: "deny-external-after-hours", reason: "After hours restriction" }), tags: JSON.stringify(["policy", "denied"]), hoursAgo: 2 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "file_read", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "file_read", verdict: "allow", duration: 230 }), tags: JSON.stringify(["execution"]), hoursAgo: 3 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "compute_task", severity: "error", outcome: "failure", details: JSON.stringify({ toolName: "compute_task", error: "Connection timeout after retries", duration: 5000 }), tags: JSON.stringify(["execution", "error"]), hoursAgo: 4 },
    { actorId: "system", actorType: "system", action: "security.alert", resource: "tool", resourceName: "security_scan", severity: "critical", outcome: "denied", details: JSON.stringify({ alert: "Unauthorized execution attempt", toolName: "security_scan", blockedBy: "RBAC" }), tags: JSON.stringify(["security", "alert", "critical"]), hoursAgo: 5 },
    { actorId: "system", actorType: "system", action: "server.health_check", resource: "server", resourceName: "primary-gateway", severity: "info", outcome: "success", details: JSON.stringify({ serverName: "primary-gateway", status: "healthy", responseTime: 45 }), tags: JSON.stringify(["monitoring", "health"]), hoursAgo: 6 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "metrics_collect", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "metrics_collect", verdict: "allow", duration: 890 }), tags: JSON.stringify(["execution"]), hoursAgo: 8 },
    { actorId: adminUserId, actorType: "user", action: "policy.create", resource: "policy", resourceName: "business-hours-only", severity: "info", outcome: "success", details: JSON.stringify({ policyName: "business-hours-only", effect: "require_approval" }), tags: JSON.stringify(["policy"]), hoursAgo: 10 },
    { actorId: "system", actorType: "system", action: "tool.execute", resource: "tool", resourceName: "email_send", severity: "warn", outcome: "denied", details: JSON.stringify({ toolName: "email_send", verdict: "deny", reason: "Rate limit exceeded" }), tags: JSON.stringify(["execution", "rate-limit"]), hoursAgo: 12 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "webhook_dispatch", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "webhook_dispatch", verdict: "allow", duration: 320 }), tags: JSON.stringify(["execution"]), hoursAgo: 14 },
    { actorId: "system", actorType: "system", action: "resource.low_stock", resource: "inventory", resourceName: "Inventory", severity: "warn", outcome: "success", details: JSON.stringify({ alert: "Low stock (5 items)", sku: "WH-0042" }), tags: JSON.stringify(["inventory", "alert"]), hoursAgo: 16 },
    { actorId: adminUserId, actorType: "user", action: "role.assign", resource: "role", resourceName: "superadmin", severity: "info", outcome: "success", details: JSON.stringify({ targetUserId: adminUserId, role: "superadmin" }), tags: JSON.stringify(["rbac"]), hoursAgo: 18 },
    { actorId: "system", actorType: "system", action: "server.health_check", resource: "server", resourceName: "notification-hub", severity: "error", outcome: "failure", details: JSON.stringify({ serverName: "notification-hub", status: "unhealthy", error: "SMTP timeout" }), tags: JSON.stringify(["monitoring", "health", "error"]), hoursAgo: 20 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "inventory_check", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "inventory_check", verdict: "allow", duration: 150 }), tags: JSON.stringify(["execution"]), hoursAgo: 22 },
    { actorId: "system", actorType: "system", action: "security.alert", resource: "tool", resourceName: "compute_task", severity: "critical", outcome: "denied", details: JSON.stringify({ alert: "GPU resource abuse attempt", toolName: "compute_task", blockedBy: "Policy Engine" }), tags: JSON.stringify(["security", "alert", "critical"]), hoursAgo: 23 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "schema_mapper", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "schema_mapper", verdict: "conditional", duration: 1200 }), tags: JSON.stringify(["execution"]), hoursAgo: 30 },
    { actorId: "system", actorType: "system", action: "policy.evaluate", resource: "policy", resourceName: "rate-limit-operators", severity: "warn", outcome: "success", details: JSON.stringify({ policyName: "rate-limit-operators", remainingQuota: 3, window: "1h" }), tags: JSON.stringify(["policy", "quota"]), hoursAgo: 36 },
    { actorId: adminUserId, actorType: "user", action: "tool.execute", resource: "tool", resourceName: "weather_lookup", severity: "info", outcome: "success", details: JSON.stringify({ toolName: "weather_lookup", verdict: "allow", duration: 380 }), tags: JSON.stringify(["execution"]), hoursAgo: 40 },
  ];
}
