import type { NichoIndustrial } from "./_types";

export const NICHOS_INDUSTRIALES_PART1: NichoIndustrial[] = [
  // ─── SALUD ──────────────────────────────────────────────────────
  {
    id: "healthtech",
    nombre: "Telemedicina y Salud",
    icono: "Heart",
    emoji: "💚",
    standard: "HIPAA",
    standardNombre: "Health Insurance Portability and Accountability Act",
    standardDescripcion: "Protección de datos de pacientes y registros médicos electrónicos en entornos de telemedicina",
    reglas: [
      "Cifrado obligatorio de datos de pacientes (en tránsito y en reposo)",
      "Auditoría de acceso a historiales clínicos con trazabilidad",
      "Consentimiento informado digital requerido antes de cualquier acción",
      "Separación de datos clínicos y administrativos",
      "Retención mínima de 6 años de registros de acceso",
    ],
    denyAbsolutos: [
      "La IA nunca puede modificar recetas médicas directamente",
      "La IA nunca puede diagnosticar sin validación humana",
      "La IA nunca puede acceder a datos de pacientes sin autorización explícita",
    ],
    color: "emerald",
    categoria: "salud",
  },
  {
    id: "pharma",
    nombre: "Farmacéutica",
    icono: "Pill",
    emoji: "💊",
    standard: "FDA 21 CFR Part 11 / GxP",
    standardNombre: "Code of Federal Regulations Title 21 — Electronic Records & Signatures",
    standardDescripcion: "Regulación de registros electrónicos y firmas digitales en la industria farmacéutica",
    reglas: [
      "Trazabilidad completa de cada lote de producción",
      "Firmas electrónicas con integridad garantizada",
      "Validación de sistemas computarizados según GAMP5",
      "Control de cambios documentado y aprobado",
    ],
    denyAbsolutos: [
      "La IA nunca puede aprobar liberación de lotes sin firma humana",
      "La IA nunca puede alterar datos de ensayos clínicos",
    ],
    color: "teal",
    categoria: "salud",
  },
  {
    id: "biotech",
    nombre: "Biotecnología",
    icono: "Microscope",
    emoji: "🔬",
    standard: "ISO 13485 / GLP",
    standardNombre: "Gestiónd de Calidad en Dispositivos Médicos / Buenas Prácticas de Laboratorio",
    standardDescripcion: "Calidad y seguridad en investigación biotecnológica y desarrollo de dispositivos médicos",
    reglas: [
      "Registro inmutable de experimentos y resultados",
      "Control de acceso basado en roles para datos de investigación",
      "Auditoría de modificaciones en protocolos experimentales",
    ],
    denyAbsolutos: [
      "La IA nunca puede fabricar resultados de investigación",
      "La IA nunca puede autorizar uso de material biológico sin aprobación",
    ],
    color: "lime",
    categoria: "salud",
  },
  {
    id: "health_insur",
    nombre: "Seguros de Salud",
    icono: "Stethoscope",
    emoji: "🩺",
    standard: "HIPAA / ACA",
    standardNombre: "Affordable Care Act — Regulaciones de Seguros de Salud",
    standardDescripcion: "Protección de datos de pacientes y cumplimiento en procesamiento de reclamos de salud",
    reglas: [
      "Verificación de elegibilidad antes de procesar reclamos",
      "Cifrado de información médica en todas las transacciones",
      "Auditoría de acceso a registros de pacientes asegurados",
    ],
    denyAbsolutos: [
      "La IA nunca puede denegar cobertura médica de forma autónoma",
      "La IA nunca puede acceder a historiales médicos sin autorización HIPAA",
    ],
    color: "green",
    categoria: "salud",
  },

  // ─── FINANCIERO ─────────────────────────────────────────────────
  {
    id: "fintech",
    nombre: "Fintech y Pagos",
    icono: "Landmark",
    emoji: "🏦",
    standard: "PCI-DSS / AML/KYC",
    standardNombre: "Payment Card Industry Data Security Standard / Anti-Money Laundering",
    standardDescripcion: "Seguridad de datos de tarjetas y prevención de lavado de dinero en servicios financieros",
    reglas: [
      "Tokenización obligatoria de datos de tarjetas",
      "Registro inmutable de todas las transacciones",
      "Aprobación humana para transferencias mayores a $10,000",
      "Verificación de identidad KYC antes de apertura de cuentas",
    ],
    denyAbsolutos: [
      "La IA nunca puede ejecutar transferencias > $10,000 sin aprobación humana",
      "La IA nunca puede alterar registros de transacciones",
      "La IA nunca puede omitir verificaciones KYC/AML",
    ],
    color: "amber",
    categoria: "financiero",
  },
  {
    id: "banking",
    nombre: "Banca Digital",
    icono: "Landmark",
    emoji: "🏛️",
    standard: "Basel III / SOX",
    standardNombre: "Acuerdos de Basilea III / Sarbanes-Oxley Act",
    standardDescripcion: "Regulación de capital, liquidez y reportes financieros en banca digital",
    reglas: [
      "Reportes regulatorios automatizados con trazabilidad",
      "Control de acceso multinivel a sistemas centrales",
      "Conciliación automática con validación humana",
    ],
    denyAbsolutos: [
      "La IA nunca puede modificar balances contables sin auditoría",
      "La IA nunca puede generar reportes regulatorios falsos",
    ],
    color: "yellow",
    categoria: "financiero",
  },
  {
    id: "insurance",
    nombre: "Seguros",
    icono: "ShieldCheck",
    emoji: "🛡️",
    standard: "Solvency II / NAIC",
    standardNombre: "Directiva de Solvencia II / National Association of Insurance Commissioners",
    standardDescripcion: "Requisitos de capital y gobernanza para compañías de seguros",
    reglas: [
      "Cálculo de reservas con auditoría automática",
      "Registro de pólizas y siniestros con cadena inmutable",
      "Validación humana para siniestros mayores al umbral",
    ],
    denyAbsolutos: [
      "La IA nunca puede aprobar siniestros de alto valor sin revisión humana",
      "La IA nunca puede modificar términos de pólizas vigentes",
    ],
    color: "orange",
    categoria: "financiero",
  },
  {
    id: "crypto",
    nombre: "Criptoactivos y DeFi",
    icono: "Waves",
    emoji: "₿",
    standard: "MiCA / FATF Travel Rule",
    standardNombre: "Markets in Crypto-Assets / Financial Action Task Force",
    standardDescripcion: "Regulación de criptoactivos y prevención de lavado de dinero en finanzas descentralizadas",
    reglas: [
      "Verificación de contraparte en cada transacción",
      "Registro inmutable de operaciones on-chain/off-chain",
      "Monitoreo de patrones de lavado de dinero",
    ],
    denyAbsolutos: [
      "La IA nunca puede ejecutar transacciones de mezcla (mixing) de fondos",
      "La IA nunca puede eludir controles de Travel Rule",
    ],
    color: "purple",
    categoria: "financiero",
  },

  // ─── EDUCACIÓN ──────────────────────────────────────────────────
  {
    id: "edtech",
    nombre: "Tecnología Educativa",
    icono: "GraduationCap",
    emoji: "🎓",
    standard: "COPPA / FERPA",
    standardNombre: "Children's Online Privacy Protection Act / Family Educational Rights and Privacy Act",
    standardDescripcion: "Protección de datos de menores y registros estudiantiles en plataformas educativas",
    reglas: [
      "Protección de datos de menores de 13 años",
      "Consentimiento parental verificado para menores",
      "Anonimización de registros estudiantiles en análisis",
      "Derecho a eliminación de datos personales",
    ],
    denyAbsolutos: [
      "La IA nunca puede generar calificaciones sin intervención docente",
      "La IA nunca puede recopilar datos de menores sin consentimiento parental",
    ],
    color: "blue",
    categoria: "educacion",
  },
  {
    id: "highered",
    nombre: "Educación Superior",
    icono: "GraduationCap",
    emoji: "📚",
    standard: "FERPA / GDPR",
    standardNombre: "Family Educational Rights and Privacy Act / General Data Protection Regulation",
    standardDescripcion: "Protección de datos académicos e investigación en instituciones de educación superior",
    reglas: [
      "Control de acceso granular a expedientes académicos",
      "Auditoría de acceso a datos de investigación",
      "Consentimiento informado para uso de datos en investigación",
    ],
    denyAbsolutos: [
      "La IA nunca puede alterar expedientes académicos",
      "La IA nunca puede usar datos de investigación sin consentimiento",
    ],
    color: "sky",
    categoria: "educacion",
  },
  {
    id: "corptraining",
    nombre: "Capacitación Corporativa",
    icono: "Workflow",
    emoji: "📋",
    standard: "SCORM / ISO 10015",
    standardNombre: "Sharable Content Object Reference Model / Gestión de Calidad en Capacitación",
    standardDescripcion: "Estándares de contenido educativo y gestión de calidad en capacitación empresarial",
    reglas: [
      "Registro inmutable de certificaciones obtenidas",
      "Trazabilidad de cumplimiento de programas de capacitación",
      "Validación de competencias con evidencia documentada",
    ],
    denyAbsolutos: [
      "La IA nunca puede certificar competencias sin evaluación humana",
      "La IA nunca puede falsificar registros de capacitación",
    ],
    color: "indigo",
    categoria: "educacion",
  },

  // ─── LEGAL ──────────────────────────────────────────────────────
  {
    id: "legaltech",
    nombre: "Tecnología Legal",
    icono: "Scale",
    emoji: "⚖️",
    standard: "ABA / GDPR",
    standardNombre: "American Bar Association / General Data Protection Regulation",
    standardDescripcion: "Protección del privilegio abogado-cliente y datos personales en tecnología legal",
    reglas: [
      "Privilegio abogado-cliente protegido por diseño",
      "Retención documental por jurisdicción",
      "No generación de opiniones legales por IA",
      "Cadena de custodia digital para evidencia",
    ],
    denyAbsolutos: [
      "La IA nunca puede generar opiniones legales vinculantes",
      "La IA nunca puede revelar comunicaciones privilegiadas",
      "La IA nunca puede alterar documentos legales sin bitácora",
    ],
    color: "rose",
    categoria: "legal",
  },
  {
    id: "compliance",
    nombre: "Cumplimiento Regulatorio",
    icono: "ShieldCheck",
    emoji: "📜",
    standard: "SOX / ISO 37301",
    standardNombre: "Sarbanes-Oxley Act / Compliance Management Systems",
    standardDescripcion: "Sistemas de gestión de cumplimiento y reportes regulatorios corporativos",
    reglas: [
      "Reportes de cumplimiento con firma digital inmutable",
      "Mapeo de regulaciones a controles internos",
      "Auditoría continua de desviaciones regulatorias",
    ],
    denyAbsolutos: [
      "La IA nunca puede ocultar violaciones regulatorias",
      "La IA nunca puede alterar reportes de cumplimiento",
    ],
    color: "pink",
    categoria: "legal",
  },
  {
    id: "ip",
    nombre: "Propiedad Intelectual",
    icono: "Lock",
    emoji: "🔒",
    standard: "WIPO / TRIPS",
    standardNombre: "World Intellectual Property Organization / Trade-Related Aspects of IP Rights",
    standardDescripcion: "Protección y gestión de patentes, marcas y derechos de autor",
    reglas: [
      "Registro de creación con sello temporal inmutable",
      "Control de acceso a documentos de patentes pendientes",
      "Auditoría de uso de propiedad intelectual",
    ],
    denyAbsolutos: [
      "La IA nunca puede plagiar contenido protegido",
      "La IA nunca puede revelar secretos comerciales",
    ],
    color: "fuchsia",
    categoria: "legal",
  },
];
