import type { NichoIndustrial } from "./_types";

export const NICHOS_INDUSTRIALES_PART2: NichoIndustrial[] = [
  // ─── INDUSTRIAL ─────────────────────────────────────────────────
  {
    id: "manufacturing",
    nombre: "Manufactura Inteligente",
    icono: "Factory",
    emoji: "🏭",
    standard: "ISO 27001",
    standardNombre: "International Standard for Information Security Management",
    standardDescripcion: "Gestión de seguridad de la información en entornos de manufactura inteligente",
    reglas: [
      "Control de acceso a sistemas SCADA",
      "Registro de modificaciones en líneas de producción",
      "Validación humana para cambios críticos en procesos",
      "Monitoreo de integridad de sensores IoT",
    ],
    denyAbsolutos: [
      "La IA nunca puede modificar parámetros de seguridad de planta sin autorización",
      "La IA nunca puede desactivar sistemas de alarma industrial",
    ],
    color: "slate",
    categoria: "industrial",
  },
  {
    id: "supplychain",
    nombre: "Cadena de Suministro",
    icono: "Truck",
    emoji: "🚛",
    standard: "ISO 28000 / C-TPAT",
    standardNombre: "Supply Chain Security Management / Customs-Trade Partnership Against Terrorism",
    standardDescripcion: "Seguridad y trazabilidad en cadenas de suministro globales",
    reglas: [
      "Trazabilidad end-to-end de productos y materiales",
      "Validación de proveedores con verificación automática",
      "Registro inmutable de movimiento de mercancías",
    ],
    denyAbsolutos: [
      "La IA nunca puede alterar registros de trazabilidad",
      "La IA nunca puede autorizar ingreso de mercancías sin verificación",
    ],
    color: "stone",
    categoria: "industrial",
  },
  {
    id: "energy",
    nombre: "Energía y Utilities",
    icono: "Zap",
    emoji: "⚡",
    standard: "NERC CIP / IEC 62351",
    standardNombre: "Critical Infrastructure Protection / Power Systems Security",
    standardDescripcion: "Protección de infraestructura crítica en sector energético",
    reglas: [
      "Monitoreo de ciberseguridad en infraestructura crítica",
      "Validación humana para despacho de carga",
      "Auditoría de acceso a sistemas de control de red",
    ],
    denyAbsolutos: [
      "La IA nunca puede despachar carga eléctrica sin autorización humana",
      "La IA nunca puede desactivar protecciones de red eléctrica",
    ],
    color: "yellow",
    categoria: "industrial",
  },
  {
    id: "mining",
    nombre: "Minería y Recursos",
    icono: "TreePine",
    emoji: "⛏️",
    standard: "ISO 14001 / IFC Performance Standards",
    standardNombre: "Environmental Management / International Finance Corporation Standards",
    standardDescripcion: "Gestión ambiental y responsabilidad social en minería y recursos naturales",
    reglas: [
      "Monitoreo de impacto ambiental con registros inmutables",
      "Auditoría de cumplimiento de permisos ambientales",
      "Validación de seguridad en operaciones de alta riesgo",
    ],
    denyAbsolutos: [
      "La IA nunca puede autorizar operaciones sin permisos vigentes",
      "La IA nunca puede ocultar violaciones ambientales",
    ],
    color: "amber",
    categoria: "industrial",
  },

  // ─── PÚBLICO ───────────────────────────────────────────────────
  {
    id: "government",
    nombre: "Gobierno y Sector Público",
    icono: "Building2",
    emoji: "🏛️",
    standard: "NIST / FISMA",
    standardNombre: "National Institute of Standards and Technology / Federal Information Security Modernization Act",
    standardDescripcion: "Clasificación y protección de datos sensibles gubernamentales",
    reglas: [
      "Clasificación obligatoria de datos sensibles",
      "Cadena de custodia digital inmutable",
      "Aprobación multinivel para acceso a datos clasificados",
      "Auditoría de todas las acciones sobre datos gubernamentales",
    ],
    denyAbsolutos: [
      "La IA nunca puede desclasificar información sin autorización",
      "La IA nunca puede acceder a datos de seguridad nacional sin clearance",
      "La IA nunca puede alterar registros oficiales del estado",
    ],
    color: "blue",
    categoria: "publico",
  },
  {
    id: "defense",
    nombre: "Defensa y Seguridad Nacional",
    icono: "ShieldCheck",
    emoji: "🎖️",
    standard: "ITAR / CMMC",
    standardNombre: "International Traffic in Arms Regulations / Cybersecurity Maturity Model Certification",
    standardDescripcion: "Control de exportaciones de defensa y ciberseguridad en contratos militares",
    reglas: [
      "Control de acceso basado en clearance de seguridad",
      "Auditoría de todas las transacciones con datos controlados",
      "Aislamiento de redes con datos clasificados",
    ],
    denyAbsolutos: [
      "La IA nunca puede transferir datos controlados a sistemas no autorizados",
      "La IA nunca puede clasificar o desclasificar información militar",
    ],
    color: "red",
    categoria: "publico",
  },
  {
    id: "critical_infra",
    nombre: "Infraestructura Crítica",
    icono: "Building2",
    emoji: "🏗️",
    standard: "NIST CSF / EU NIS2",
    standardNombre: "Cybersecurity Framework / Network and Information Security Directive 2",
    standardDescripcion: "Protección de infraestructura crítica y servicios esenciales",
    reglas: [
      "Detección de anomalias en tiempo real",
      "Planes de respuesta a incidentes con validación humana",
      "Respaldo y recuperación con verificación de integridad",
    ],
    denyAbsolutos: [
      "La IA nunca puede desactivar sistemas de protección de infraestructura crítica",
      "La IA nunca puede aislar servicios esenciales sin autorización",
    ],
    color: "gray",
    categoria: "publico",
  },

  // ─── COMERCIO ──────────────────────────────────────────────────
  {
    id: "ecommerce",
    nombre: "Comercio Electrónico",
    icono: "ShoppingCart",
    emoji: "🛒",
    standard: "PCI-DSS / PSD2",
    standardNombre: "Payment Card Industry Data Security Standard / Payment Services Directive 2",
    standardDescripcion: "Seguridad de pagos y protección al consumidor en comercio electrónico",
    reglas: [
      "Tokenización de datos de pago",
      "Autenticación fuerte del cliente (SCA)",
      "Protección contra fraude con monitoreo en tiempo real",
    ],
    denyAbsolutos: [
      "La IA nunca puede procesar pagos sin autenticación del cliente",
      "La IA nunca puede almacenar números de tarjeta sin tokenizar",
    ],
    color: "violet",
    categoria: "comercio",
  },
  {
    id: "retail",
    nombre: "Retail y Consumo",
    icono: "ShoppingCart",
    emoji: "🛍️",
    standard: "GDPR / CCPA",
    standardNombre: "General Data Protection Regulation / California Consumer Privacy Act",
    standardDescripcion: "Protección de datos de consumidores y personalización responsable",
    reglas: [
      "Consentimiento explícito para personalización",
      "Derecho de eliminación de datos personales",
      "Transparencia en uso de datos para recomendaciones",
    ],
    denyAbsolutos: [
      "La IA nunca puede usar datos de menores para publicidad dirigida",
      "La IA nunca puede discriminar precios sin transparencia",
    ],
    color: "cyan",
    categoria: "comercio",
  },
  {
    id: "realestate",
    nombre: "Bienes Raíces",
    icono: "Building2",
    emoji: "🏠",
    standard: "TRID / AML",
    standardNombre: "TILA-RESPA Integrated Disclosure / Anti-Money Laundering",
    standardDescripcion: "Transparencia en transacciones inmobiliarias y prevención de lavado de dinero",
    reglas: [
      "Divulgación obligatoria de términos de préstamos",
      "Verificación de identidad en transacciones de alto valor",
      "Registro de transacciones con trazabilidad completa",
    ],
    denyAbsolutos: [
      "La IA nunca puede aprobar transacciones inmobiliarias sin validación humana",
      "La IA nunca puede alterar documentos de propiedad",
    ],
    color: "emerald",
    categoria: "comercio",
  },

  // ─── TECNOLOGÍA ────────────────────────────────────────────────
  {
    id: "saas",
    nombre: "SaaS y Cloud",
    icono: "Cpu",
    emoji: "☁️",
    standard: "SOC 2 / ISO 27001",
    standardNombre: "Service Organization Control 2 / Information Security Management",
    standardDescripcion: "Controles de seguridad, disponibilidad y confidencialidad en servicios cloud",
    reglas: [
      "Cifrado de datos en reposo y en tránsito",
      "Control de acceso basado en roles (RBAC)",
      "Auditoría de acceso con registros inmutables",
    ],
    denyAbsolutos: [
      "La IA nunca puede acceder a datos de otros tenants",
      "La IA nunca puede desactivar controles de seguridad sin aprobación",
    ],
    color: "blue",
    categoria: "tecnologia",
  },
  {
    id: "iot",
    nombre: "IoT y Dispositivos",
    icono: "Smartphone",
    emoji: "📡",
    standard: "ETSI EN 303 645 / NIST 8259A",
    standardNombre: "Cybersecurity Standard for Consumer IoT / IoT Baseline Security",
    standardDescripcion: "Seguridad base para dispositivos IoT de consumo e industriales",
    reglas: [
      "Autenticación obligatoria en dispositivos IoT",
      "Actualizaciones de seguridad verificadas",
      "Cifrado de comunicaciones entre dispositivos y gateway",
    ],
    denyAbsolutos: [
      "La IA nunca puede desactivar actualizaciones de seguridad de dispositivos",
      "La IA nunca puede acceder a dispositivos sin autenticación",
    ],
    color: "teal",
    categoria: "tecnologia",
  },

  // ─── SERVICIOS ─────────────────────────────────────────────────
  {
    id: "travel",
    nombre: "Viajes y Hotelería",
    icono: "Plane",
    emoji: "✈️",
    standard: "PCI-DSS / GDPR",
    standardNombre: "Payment Card Industry Data Security Standard / General Data Protection Regulation",
    standardDescripcion: "Protección de datos de viajeros y seguridad de pagos en la industria de viajes",
    reglas: [
      "Cifrado de datos de pasaporte y documentos de viaje",
      "Consentimiento explícito para personalización de ofertas",
      "Registro de acceso a datos de huéspedes",
    ],
    denyAbsolutos: [
      "La IA nunca puede compartir datos de ubicación sin consentimiento",
      "La IA nunca puede procesar reservas sin confirmación del cliente",
    ],
    color: "sky",
    categoria: "servicios",
  },
  {
    id: "media",
    nombre: "Medios y Publicidad",
    icono: "Megaphone",
    emoji: "📢",
    standard: "GDPR / DSA",
    standardNombre: "General Data Protection Regulation / Digital Services Act",
    standardDescripcion: "Protección de datos y transparencia en medios digitales y publicidad programática",
    reglas: [
      "Consentimiento para tracking y publicidad personalizada",
      "Transparencia en algoritmos de recomendación",
      "Derecho de acceso y eliminación de datos de usuario",
    ],
    denyAbsolutos: [
      "La IA nunca puede generar contenido engañoso (deepfakes)",
      "La IA nunca puede segmentar audiencias con datos sensibles sin consentimiento",
    ],
    color: "pink",
    categoria: "servicios",
  },
];
