"""CodeAssembler - Project Scaffolding Mixin."""

import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger("zenic_agents.code_gen_parts.assembler")


class AssemblerScaffoldingMixin:
    """Mixin providing project scaffolding methods."""

    # ================================================================
    #  PROJECT SCAFFOLDING
    # ================================================================

    def _generate_pydantic_models(self, entities: List[Dict],
                                   project_name: str) -> str:
        """Generate Pydantic BaseModel classes from entity definitions."""
        lines = [
            f'"""',
            f'{project_name} - Data Models',
            f'Auto-generated by ZENIC-AGENTS CodeAssembler',
            f'"""',
            '',
            'from typing import Optional, List, Dict, Any',
            'from datetime import datetime',
            'from pydantic import BaseModel, Field, validator',
            '',
            '',
        ]

        for entity in entities:
            name = entity.get("name", "Item")
            fields = entity.get("fields", [])

            # Create model
            lines.append(f'class {name}Create(BaseModel):')
            lines.append(f'    """Create schema for {name}."""')
            for field in fields:
                fname = field.get("name", "field")
                ftype = self._map_type(field.get("type", "str"))
                required = field.get("required", False)
                default = field.get("default")
                if required:
                    lines.append(f'    {fname}: {ftype}')
                elif default is not None:
                    if isinstance(default, str):
                        lines.append(f'    {fname}: {ftype} = "{default}"')
                    else:
                        lines.append(f'    {fname}: {ftype} = {default}')
                else:
                    lines.append(f'    {fname}: Optional[{ftype}] = None')
            lines.append('')
            lines.append('')

            # Update model
            lines.append(f'class {name}Update(BaseModel):')
            lines.append(f'    """Update schema for {name}."""')
            for field in fields:
                fname = field.get("name", "field")
                ftype = self._map_type(field.get("type", "str"))
                lines.append(f'    {fname}: Optional[{ftype}] = None')
            lines.append('')
            lines.append('')

            # Response model
            lines.append(f'class {name}Response(BaseModel):')
            lines.append(f'    """Response schema for {name}."""')
            lines.append(f'    id: int')
            for field in fields:
                fname = field.get("name", "field")
                ftype = self._map_type(field.get("type", "str"))
                lines.append(f'    {fname}: {ftype}')
            lines.append(f'    created_at: Optional[datetime] = None')
            lines.append('')
            lines.append('')

        return '\n'.join(lines)

    def _generate_main(self, project_name: str, blocks: List[str],
                        entities: List[Dict]) -> str:
        """Generate main.py with FastAPI app wiring real blocks."""
        import_lines = [
            f'"""',
            f'{project_name} - Main Application',
            f'Auto-generated by ZENIC-AGENTS CodeAssembler',
            f'"""',
            '',
            'import os',
            'import logging',
            'import sqlite3',
            'from typing import Optional, List, Dict, Any',
            'from fastapi import FastAPI, HTTPException, Depends',
            'from fastapi.middleware.cors import CORSMiddleware',
            '',
            f'app = FastAPI(title="{project_name}", version="1.0.0")',
            '',
            'app.add_middleware(',
            '    CORSMiddleware,',
            '    allow_origins=["*"],',
            '    allow_credentials=True,',
            '    allow_methods=["*"],',
            '    allow_headers=["*"],',
            ')',
            '',
        ]

        # Import blocks
        for block_name in blocks:
            module_name = block_name
            class_name = self._block_to_class(block_name)
            import_lines.append(f'from blocks.{module_name} import {class_name}')
        import_lines.append('')
        import_lines.append('')

        # Import models if entities
        if entities:
            import_lines.append('from models import ' + ', '.join(
                self._block_to_class(e.get("name", "Item")) + "Create, " +
                self._block_to_class(e.get("name", "Item")) + "Response"
                for e in entities
            ))
            import_lines.append('')

        # Initialize blocks
        init_lines = ['logger = logging.getLogger(__name__)', '']
        for block_name in blocks:
            class_name = self._block_to_class(block_name)
            var_name = block_name
            init_lines.append(f'{var_name} = {class_name}()')
        init_lines.append('')

        # Health check
        health_lines = [
            '',
            '@app.get("/health")',
            'async def health():',
            '    return {"status": "ok", "service": "' + project_name + '"}',
            '',
        ]

        # Entity endpoints
        endpoint_lines = []
        for entity in entities:
            entity_name = entity.get("name", "Item")
            endpoint_lines.extend(self._generate_entity_endpoints(entity_name, entity))

        return '\n'.join(import_lines + init_lines + health_lines + endpoint_lines)

    def _generate_entity_endpoints(self, entity_name: str, entity: Dict) -> List[str]:
        """Generate CRUD endpoints for an entity.

        Uses sqlite3 directly instead of async DatabaseExecutor
        so endpoints work synchronously within FastAPI async handlers.
        """
        cls = self._block_to_class(entity_name)
        table = entity_name.lower() + "s"
        lines = [
            f'',
            f'# ── {entity_name} endpoints ──',
            f'',
            f'@app.post("/v1/{table}")',
            f'async def create_{entity_name.lower()}(data: {cls}Create):',
            f'    """Create a new {entity_name}."""',
            f'    conn = sqlite3.connect(settings.DATABASE_PATH)',
            f'    try:',
            f'        data_dict = data.dict()',
            f'        columns = list(data_dict.keys())',
            f'        values = list(data_dict.values())',
            f'        placeholders = ", ".join(["?" for _ in columns])',
            f'        col_str = ", ".join(columns)',
            f'        cursor = conn.execute(',
            f'            "INSERT INTO {table} (" + col_str + ") VALUES (" + placeholders + ")", values',
            f'        )',
            f'        conn.commit()',
            f'        item_id = cursor.lastrowid',
            f'    finally:',
            f'        conn.close()',
            f'    return {{"success": True, "id": item_id, "entity": "{entity_name}"}}',
            f'',
            f'@app.get("/v1/{table}/{{item_id}}")',
            f'async def get_{entity_name.lower()}(item_id: int):',
            f'    """Get {entity_name} by ID."""',
            f'    conn = sqlite3.connect(settings.DATABASE_PATH)',
            f'    conn.row_factory = sqlite3.Row',
            f'    try:',
            f'        cursor = conn.execute("SELECT * FROM {table} WHERE id = ?", (item_id,))',
            f'        row = cursor.fetchone()',
            f'    finally:',
            f'        conn.close()',
            f'    if not row:',
            f'        raise HTTPException(status_code=404, detail="{entity_name} not found")',
            f'    return dict(row)',
            f'',
            f'@app.get("/v1/{table}")',
            f'async def list_{entity_name.lower()}(limit: int = 50, offset: int = 0):',
            f'    """List all {entity_name}s."""',
            f'    conn = sqlite3.connect(settings.DATABASE_PATH)',
            f'    conn.row_factory = sqlite3.Row',
            f'    try:',
            f'        cursor = conn.execute("SELECT * FROM {table} LIMIT ? OFFSET ?", (limit, offset))',
            f'        rows = [dict(r) for r in cursor.fetchall()]',
            f'    finally:',
            f'        conn.close()',
            f'    return {{"data": rows, "count": len(rows)}}',
            f'',
            f'@app.put("/v1/{table}/{{item_id}}")',
            f'async def update_{entity_name.lower()}(item_id: int, data: {cls}Create):',
            f'    """Update {entity_name} by ID."""',
            f'    conn = sqlite3.connect(settings.DATABASE_PATH)',
            f'    try:',
            f'        data_dict = data.dict(exclude_unset=True)',
            f'        set_parts = [str(k) + " = ?" for k in data_dict.keys()]',
            f'        set_clause = ", ".join(set_parts)',
            f'        values = list(data_dict.values()) + [item_id]',
            f'        conn.execute("UPDATE {table} SET " + set_clause + " WHERE id = ?", values)',
            f'        conn.commit()',
            f'    finally:',
            f'        conn.close()',
            f'    return {{"success": True, "id": item_id, "entity": "{entity_name}"}}',
            f'',
            f'@app.delete("/v1/{table}/{{item_id}}")',
            f'async def delete_{entity_name.lower()}(item_id: int):',
            f'    """Delete {entity_name} by ID."""',
            f'    conn = sqlite3.connect(settings.DATABASE_PATH)',
            f'    try:',
            f'        conn.execute("DELETE FROM {table} WHERE id = ?", (item_id,))',
            f'        conn.commit()',
            f'    finally:',
            f'        conn.close()',
            f'    return {{"success": True, "id": item_id, "entity": "{entity_name}"}}',
        ]
        return lines

    def _generate_requirements(self, blocks: List[str]) -> str:
        """Generate requirements.txt based on blocks used."""
        requirements = {
            "fastapi>=0.100.0",
            "uvicorn>=0.23.0",
            "pydantic>=2.0.0",
        }

        block_deps = {
            "jwt_auth": {"python-jose[cryptography]>=3.3.0", "passlib[bcrypt]>=1.7.4"},
            "stripe_payments": {"stripe>=7.0.0"},
            "email_smtp": {"aiosmtplib>=3.0.0"},
            "telegram_bot": {"aiohttp>=3.8.0"},
            "webhook_server": {"aiohttp>=3.8.0"},
            "pdf_generator": {"reportlab>=4.0.0"},
            "google_sheets": {"google-api-python-client>=2.0.0"},
            "crud_service": set(),
            "backup_restore": set(),
            "seed_data": set(),
            "notification_manager": {"aiosmtplib>=3.0.0"},
            "data_analyzer": set(),
            "inventory_tracker": set(),
            "invoice_calculator": set(),
            "crm_pipeline": set(),
            "report_generator": {"reportlab>=4.0.0"},
            "rbac": set(),
            "api_key_auth": set(),
            "database_migrations": set(),
        }

        for block in blocks:
            deps = block_deps.get(block, set())
            requirements.update(deps)

        return '\n'.join(sorted(requirements)) + '\n'

    def _generate_config(self, project_name: str, entities: List[Dict]) -> str:
        """Generate config.py with settings."""
        return f'''"""
{project_name} - Configuration
Auto-generated by ZENIC-AGENTS CodeAssembler
"""

import os
from typing import Optional


class Settings:
    """Application settings loaded from environment variables."""

    # App
    APP_NAME: str = "{project_name}"
    DEBUG: bool = os.getenv("DEBUG", "false").lower() == "true"
    PORT: int = int(os.getenv("PORT", "5000"))

    # Database
    DATABASE_PATH: str = os.getenv("DATABASE_PATH", "{project_name}.sqlite")

    # Auth (if jwt_auth block used)
    SECRET_KEY: str = os.getenv("SECRET_KEY", "change-me-in-production")
    ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "30"))

    # CORS
    CORS_ORIGINS: str = os.getenv("CORS_ORIGINS", "*")


settings = Settings()
'''
