//! Session management for Zenic-Agents.
//!
//! A [`Session`] represents an active connection from a user or service
//! within a tenant. Sessions are created by the orchestrator and carry
//! the tenant context needed for policy evaluation and multi-tenancy
//! isolation. Each session has a unique [`SessionId`] and belongs to
//! exactly one [`TenantId`].

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use zenic_proto::{SessionId, TenantId};

use crate::errors::CoreError;

// ---------------------------------------------------------------------------
// Session
// ---------------------------------------------------------------------------

/// An active session within the Zenic-Agents orchestrator.
///
/// Sessions are the unit of multi-tenancy isolation. All operations
/// performed within a session are scoped to the session's tenant.
/// The policy engine uses the session ID to look up role assignments
/// and enforce access control.
///
/// Sessions can also carry arbitrary metadata (key-value pairs) that
/// is useful for downstream subsystems, such as user preferences,
/// client version, or locale.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Session {
    /// Unique identifier for this session.
    pub session_id: SessionId,
    /// The tenant this session belongs to.
    pub tenant_id: TenantId,
    /// When this session was created (milliseconds since epoch).
    pub created_at_ms: u64,
    /// Arbitrary metadata attached to this session.
    pub metadata: HashMap<String, String>,
}

impl Session {
    /// Creates a new session for the given tenant.
    pub fn new(session_id: SessionId, tenant_id: TenantId, created_at_ms: u64) -> Self {
        Self {
            session_id,
            tenant_id,
            created_at_ms,
            metadata: HashMap::new(),
        }
    }

    /// Adds a metadata entry to the session.
    pub fn with_metadata(mut self, key: &str, value: &str) -> Self {
        self.metadata.insert(key.to_string(), value.to_string());
        self
    }

    /// Sets a metadata entry (mutable).
    pub fn set_metadata(&mut self, key: &str, value: &str) {
        self.metadata.insert(key.to_string(), value.to_string());
    }

    /// Retrieves a metadata entry.
    pub fn get_metadata(&self, key: &str) -> Option<&str> {
        self.metadata.get(key).map(|s| s.as_str())
    }

    /// Validates the session for internal consistency.
    pub fn validate(&self) -> Result<(), CoreError> {
        // Sessions always have valid IDs (generated by SessionId::new),
        // so there is not much to validate. We keep this method as a
        // placeholder for future validation requirements.
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// SessionStore
// ---------------------------------------------------------------------------

/// In-memory store for active sessions.
///
/// The session store maps session IDs to their session objects.
/// It enforces the maximum concurrent session limit configured
/// in the orchestrator.
pub struct SessionStore {
    sessions: HashMap<SessionId, Session>,
    max_sessions: usize,
}

impl SessionStore {
    /// Creates a new session store with a maximum capacity.
    pub fn new(max_sessions: usize) -> Self {
        Self {
            sessions: HashMap::new(),
            max_sessions,
        }
    }

    /// Creates a new session and adds it to the store.
    ///
    /// Returns an error if the maximum session limit has been reached.
    pub fn create(
        &mut self,
        tenant_id: TenantId,
        created_at_ms: u64,
    ) -> Result<Session, CoreError> {
        if self.sessions.len() >= self.max_sessions {
            return Err(CoreError::General(format!(
                "maximum session limit reached ({} sessions)",
                self.max_sessions
            )));
        }
        let session = Session::new(SessionId::new(), tenant_id, created_at_ms);
        self.sessions.insert(session.session_id, session.clone());
        Ok(session)
    }

    /// Retrieves a session by its ID.
    pub fn get(&self, session_id: &SessionId) -> Option<&Session> {
        self.sessions.get(session_id)
    }

    /// Removes a session from the store.
    pub fn remove(&mut self, session_id: &SessionId) -> Option<Session> {
        self.sessions.remove(session_id)
    }

    /// Returns the number of active sessions.
    pub fn len(&self) -> usize {
        self.sessions.len()
    }

    /// Whether the store is empty.
    pub fn is_empty(&self) -> bool {
        self.sessions.is_empty()
    }

    /// Returns the maximum session capacity.
    pub fn capacity(&self) -> usize {
        self.max_sessions
    }

    /// Returns all sessions for a tenant.
    pub fn sessions_for_tenant(&self, tenant_id: &TenantId) -> Vec<&Session> {
        self.sessions
            .values()
            .filter(|s| &s.tenant_id == tenant_id)
            .collect()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_new() {
        let sid = SessionId::new();
        let tid = TenantId::new();
        let session = Session::new(sid, tid, 1000);
        assert_eq!(session.session_id, sid);
        assert_eq!(session.tenant_id, tid);
        assert_eq!(session.created_at_ms, 1000);
        assert!(session.metadata.is_empty());
    }

    #[test]
    fn session_with_metadata() {
        let session = Session::new(SessionId::new(), TenantId::new(), 0)
            .with_metadata("user", "alice")
            .with_metadata("locale", "es");
        assert_eq!(session.get_metadata("user"), Some("alice"));
        assert_eq!(session.get_metadata("locale"), Some("es"));
        assert_eq!(session.get_metadata("missing"), None);
    }

    #[test]
    fn session_set_metadata_mutable() {
        let mut session = Session::new(SessionId::new(), TenantId::new(), 0);
        session.set_metadata("key", "value");
        assert_eq!(session.get_metadata("key"), Some("value"));
    }

    #[test]
    fn session_validate_ok() {
        let session = Session::new(SessionId::new(), TenantId::new(), 0);
        assert!(session.validate().is_ok());
    }

    #[test]
    fn session_store_create_and_get() {
        let mut store = SessionStore::new(10);
        let tid = TenantId::new();
        let session = store.create(tid, 1000).expect("create");
        let sid = session.session_id;

        assert_eq!(store.len(), 1);
        let retrieved = store.get(&sid);
        assert!(retrieved.is_some());
        assert_eq!(retrieved.unwrap().tenant_id, tid);
    }

    #[test]
    fn session_store_remove() {
        let mut store = SessionStore::new(10);
        let session = store.create(TenantId::new(), 0).expect("create");
        let sid = session.session_id;

        let removed = store.remove(&sid);
        assert!(removed.is_some());
        assert!(store.is_empty());
        assert!(store.get(&sid).is_none());
    }

    #[test]
    fn session_store_max_sessions() {
        let mut store = SessionStore::new(2);
        store.create(TenantId::new(), 0).expect("create 1");
        store.create(TenantId::new(), 0).expect("create 2");
        let result = store.create(TenantId::new(), 0);
        assert!(result.is_err());
    }

    #[test]
    fn session_store_sessions_for_tenant() {
        let mut store = SessionStore::new(10);
        let tid1 = TenantId::new();
        let tid2 = TenantId::new();
        store.create(tid1, 0).expect("create 1");
        store.create(tid1, 0).expect("create 2");
        store.create(tid2, 0).expect("create 3");

        let tid1_sessions = store.sessions_for_tenant(&tid1);
        let tid2_sessions = store.sessions_for_tenant(&tid2);
        assert_eq!(tid1_sessions.len(), 2);
        assert_eq!(tid2_sessions.len(), 1);
    }

    #[test]
    fn session_store_capacity() {
        let store = SessionStore::new(50);
        assert_eq!(store.capacity(), 50);
    }
}
